### ISSUE TITLE
Add Option to Deduplicate Facts from Traditional XBRL

### ISSUE THREAD

**Issue by austinmatherne-wk** [Arelle/Arelle#1002]
### What should we change and why?

We should reuse the implementation in #1001 to offer the ability to deduplicate complete or consistent facts from traditional XBRL instance documents.

```bash
python arelleCmdLine.py --file instance.xml --deduplicateFacts=consistent --saveDeduplicateInstance=report-deduplicated.xml
```

`--deduplicateFacts` should default to `complete` and an exception should be raised if `--deduplicateFacts` is used without `--saveDeduplicateInstance`.

* [ ] complete duplicates.
* [ ] consistent duplicates (the more precise fact should be preserved).

**Comment by hermfischer-wf** [comment]
How will this affect the Arelle and ixviewer-plus implementations, both require each inline-located duplicated fact to have an id matching its extracted instance facts, usually the face statement facts are less precise than the disclosure locations of the same fact.  Each html location of the duplicated fact will have a different ID so the proper duplicate fact can be matched to the html location of each reference.

**Comment by austinmatherne-wk** [comment]
Deduplicating facts within the context of viewer plugins and multi ixds isn't particularly useful. We could block those combinations, but it's simpler and probably more useful to make this a separate operation on single traditional XBRL instance documents.

```bash
python arelleCmdLine.py ... --file=report.htm --saveInstance=report.xml
python arelleCmdLine.py --file=report.xml --deduplicateFacts=consistent --saveDeduplicate=report-deduplicated.xml
```
