### ISSUE TITLE
ESEF error message refers to old DTR version

### ISSUE THREAD

**Issue by paulwarren-wk** [Arelle/Arelle#1030]
### What happened?

The ESEF validator produces the following error message:

> Domain members MUST have domainItemType data type as defined in \"http://www.xbrl.org/dtr/type/nonNumeric-2009-12-16.xsd

(see https://github.com/Arelle/Arelle/blob/master/arelle/plugin/validate/ESEF/ESEF_Current/DTS.py#L208)

But ESEF 2023 requires the 2020 DTR (see https://github.com/Arelle/Arelle/blob/master/arelle/plugin/validate/ESEF/Const.py#L89)

i.e. validation appears to be correct, but error message is wrong.

### Interface

CLI (arelleCmdLine), GUI (arelleGUI)

### Version

0975615971ef93de11d19b59bc5cf8750bb1b9d1

### Download

From source (git checkout)

### Operating System

Linux (Ubuntu 22.04)

**Comment by gmongelli** [comment]
Hello Paul,

Thank you for the error report and we hereby confirm the issue.

The error message needs to be customised according to the disclosure system. We'll do that as soon as possible.

Best regards,

Greg
