### ISSUE TITLE
ESEF-dqc rule set map points to invalid ruleset

### ISSUE THREAD

**Issue by fantastic-shaun** [Arelle/Arelle#1040]
### What happened?

When running the ESEF-dqc validation I get a log message "[info] Using ruleset **None** - 1234567890-2022-12-31-T01.xhtml". It appears Arelle can't see a ruleset. 

When I select TOOLS>ESEF-dqc>Display ESEF-dqc Rule set map, I get the following error message. 
OSError: Unable to open file: https://github.com/DataQualityCommittee/dqc_us_rules/raw/v22/dqc_us_rules/dqc-esef-2023-V22-ruleset.zip

![arelle_esef-dqc_error](https://github.com/Arelle/Arelle/assets/156697549/eb8dd58f-cd05-4717-b286-20154f5cb4fd)

Looking at that location, an esef 2023 v22 zip file doesn't exist.
I am unclear whether the URL is incorrect or whether the zip file is missing.

### Interface

GUI (arelleGUI)

### Version

2.21.3

### Download

arelle.org (bundled Python)

### Operating System

Windows 11

**Comment by gmongelli** [comment]
Hello,

The DQC plug-in is not part of the Arelle core.

Without too much knowledge about that plug-in, have a look at https://github.com/DataQualityCommittee/dqc_us_rules/

They seem to be responsible for the missing ZIP files.

Best regards,

Greg

**Comment by fantastic-shaun** [comment]
Many thanks for your reply.

Shaun Curran

Fantastic Ideas
e: ***@***.***
m: 0790 0690 466
linkedin: https://www.linkedin.com/in/shauncurran/
w: www.fantastic-ideas.com

Registered in England and Wales, Company Number 6616136
​
Broadthorn,
​ Armstrong Lane, Brockenhurst, Hampshire SO42 7SY
