### ISSUE TITLE
Command line folder package problem

### ISSUE THREAD

**Issue by kris2kris** [Arelle/Arelle#1053]
### What happened?

I use command line to execute arelle with the option --packages, when I try to migrate to the new way to import packages (by setting a folder instead of all .zip with the | separator) the xbrl files are not correctly opened.
I suppose the problem is the order of loading because all packages seem to be loaded but not in same order, is there any way to order packages import from a folder ?

### Interface

CLI (arelleCmdLine)

### Version

2.21.1

### Download

GitHub release (bundled Python)

### Operating System

Linux (Ubuntu 22.04)

**Comment by austinmatherne-wk** [comment]
No, but the order really shouldn't matter unless you're loading incompatible packages (they have conflicting files). You can also use multiple arguments to specify multiple packages without using the `|` syntax (`--package taxonomy.1.zip --package taxonomy.2.zip`, etc.)
