### ISSUE TITLE
Regression - Labels no longer display in Arelle GUI

### ISSUE THREAD

**Issue by michaelchadfleming** [Arelle/Arelle#1089]
### What happened?

Open any taxonomy. Try to change the label role to either standard label, terse label, or documentation and it always shows the name. Please see image

![image](https://github.com/Arelle/Arelle/assets/133998455/10bc02f9-e659-40d0-bfa6-9e8a9df4835f)

### Documents

Open from web: https://xbrl.sec.gov/dei/2023/dei-entire-2023.xsd

### Interface

GUI (arelleGUI)

### Version

2.23.8

### Download

arelle.org (bundled Python)

### Operating System

Windows 10

**Comment by austinmatherne-wk** [comment]
Hi @michaelchadfleming,

Can you provide a screenshot of the "Tools" > "Language..." menu?

**Comment by michaelchadfleming** [comment]
Hi @austinmatherne-wk 

Thank you for the quick response. Please see the requested screenshot below :). They were both en-GB. Thank you for adding the new story to fix the language. In addition, I updated both to "English (United States)" and I now get error 500 internal server error after being first redirected to http://localhost:52949/2/ix?doc=/2/akr-20231231.htm&xbrl=true?redline=true

![image](https://github.com/Arelle/Arelle/assets/133998455/590add11-8089-4a8f-b2cb-080e3d3c62b0)
![image](https://github.com/Arelle/Arelle/assets/133998455/1ac3243f-f3e9-45e3-8a7d-4494df654e9d)
![image](https://github.com/Arelle/Arelle/assets/133998455/992386f3-fff4-4455-a09d-db239b02bd63)

**Comment by austinmatherne-wk** [comment]
Hi @michaelchadfleming,

I just made a new release (2.23.10) that should resolve the label issue.

Regarding the 500 internal server error. It's not clear to me what precise steps caused that. Did you already have a viewer open when you changed the language? Was it redirected when you clicked "OK" from the language settings dialog? Is this specific to changing languages or are there other causes?

If you can open a new issue for that with more details I'd be happy to look into it.

**Comment by michaelchadfleming** [comment]
@austinmatherne-wk Thank you for the new, fixed build :) The other issue with 500 error occurs kind of frequently for me. It mainly happens almost every time I install the DQC plug-in. I'll try to create a new issue for this in the future.
