### ISSUE TITLE
Migrate loadFromOIM Plugin Into Core Arelle

### ISSUE THREAD

**Issue by austinmatherne-wk** [Arelle/Arelle#1100]
### What should we change and why?

The [loadFromOIM](https://github.com/Arelle/Arelle/blob/42dcb76e2d8f9563df13ee8e5a357f2d2cb0b80c/arelle/plugin/loadFromOIM.py) plugin implements support for the [OIM specification](https://specifications.xbrl.org/work-product-index-open-information-model-open-information-model.html). Core XBRL support should not require plugins.

The code implemented with plugin hooks should be moved into core Arelle without the use of plugin hooks. [xBRL-XML OIM validation](https://github.com/Arelle/Arelle/blob/42dcb76e2d8f9563df13ee8e5a357f2d2cb0b80c/arelle/plugin/loadFromOIM.py#L2912) should be behind a new command line argument `--oim`, GUI validation menu option, and web server query param. The plugin should remain as a placeholder that logs a deprecation warning when used from the CLI, informing users that the plugin is no longer necessary and will be removed in the future. If the placeholder plugin is enabled then xBRL-XML validation should also be enabled.

**Comment by brettkail-wk** [comment]
> an empty placeholder that logs a deprecation warning

I thought the problem is that the `loadFromOIM` plugin also enables OIM processing/validation for xBRL-XML (`xbrlxe:unsupportedFraction`, etc.).  If we deprecate the plugin with a warning, what would people use?  I guess we could add `--oim` that does the same thing, but why break the existing mechanism?  Is there some benefit to having the logic be "builtin" rather than loaded as a plugin?

**Comment by austinmatherne-wk** [comment]
Good call. The [xml-XML OIM validation](https://github.com/Arelle/Arelle/blob/42dcb76e2d8f9563df13ee8e5a357f2d2cb0b80c/arelle/plugin/loadFromOIM.py#L2912) needs to be behind a flag that's automatically enabled if the deprecated plugin is used.

The benefit of making base XBRL support builtin is reducing our support burden caused by issues of plugin discoverability and complexity of the command line syntax. There are 100+ plugins which makes identifying required plugins less than straightforward for new users. It's also clear from our support channels that many users don't know how to use plugins and frequently copy paste commands others have run regardless of if they make sense for their use case.
