### ISSUE TITLE
Arelle removing ix tags for SEC and CIPC jurisdiction

### ISSUE THREAD

**Issue by anilpatra023** [Arelle/Arelle#1192]
### What happened?

While validating using Arelle for SEC, non-numeric tags are getting removed.
![image](https://github.com/Arelle/Arelle/assets/168920368/1e73d286-eb7e-4bcc-bcf7-3aefcb41c831)

input file with tag is attached and output file after Arelle validation is attached.
And for CIPC all the tags are getting removed.
![image](https://github.com/Arelle/Arelle/assets/168920368/e3d4eaca-72b6-4c7c-a74f-a3b69875e8e4)

input file with tag is attached and output file after Arelle validation is attached.

Please check and let us how to resolve these issues. And also let us know do we need to do any configuration to see all the tags/facts in output file.

Note: When we are using Arelle v2.11.3, we were not facing these issues. We are able to see all the respective facts for all jurisdictions.

### Documents

[CIPC_Arelle_output.zip](https://github.com/Arelle/Arelle/files/15210156/CIPC_Arelle_output.zip)
[CIPC_input.zip](https://github.com/Arelle/Arelle/files/15210157/CIPC_input.zip)
[SEC_Arele_Output.zip](https://github.com/Arelle/Arelle/files/15210169/SEC_Arele_Output.zip)
[SEC_input.zip](https://github.com/Arelle/Arelle/files/15210170/SEC_input.zip)

### If running from the command line, what command did you run?

-f "C:\Windows\TEMP\790c1595-1539-48c1-9134-22c5abf0cdfe\renderer_in.zip" --plugins "EdgarRenderer" --disclosureSystem efm-pragmatic  --logFile "validationlog.xml" --logFormat "%(message)s - %(file)s"  -o C:\Windows\TEMP\790c1595-1539-48c1-9134-22c5abf0cdfe\rendered_out.zip --internetConnectivity=online

### Interface

CLI (arelleCmdLine)

### Version

2.25.4 , 2.26.7

### Download

GitHub release (bundled Python)

### Operating System

Windows

**Comment by austinmatherne-wk** [comment]
Hello @anilpatra023,

Thank you for reaching out. The issue you've described pertains to the EdgarRenderer and SEC plugins, which are not maintained within this repository or by the Arelle team. For issues related to these plugins, we kindly ask you to contact the SEC directly.

For your reference, as stated in [our readme](https://github.com/Arelle/Arelle#edgarrenderer-or-efm-validations):
> The SEC develops and maintains the EdgarRenderer and EFM validation plugins. Please report issues with these plugins directly to the SEC (StructuredData@sec.gov).

Kind regards,
Austin Matherne
