### ISSUE TITLE
Command line Arguement for CIPC & HMRC is not giving renderer output folder

### ISSUE THREAD

**Issue by anilpatra023** [Arelle/Arelle#1197]
### What happened?

We are trying to use command line validate our xbrl output for all jurisdictions to get renderer output, which will opened using ixviewer. For ESMA & SEC , we are getting renderer output for ixviewer, but for CIPC & HMRC, we are using below command which validating but not giving renderer output.

For CIPC:
"C:\Program Files\Arelle\arelleCmdLine.exe" -f "D:\CIPC_x_9th\renderer_in.zip"    --plugins "EdgarRenderer|validate\cipc" --validate --disclosureSystem cipc  --logFile "D:\CIPC_x_9th\validationlog.xml" --logFormat "%(message)s - %(file)s"  -o "D:\CIPC_x_9th\renderer_out.zip" --internetConnectivity offline

For HMRC:
"C:\Program Files\Arelle\arelleCmdLine.exe" -f "C:\A\renderer_in.zip" --plugins "EdgarRenderer|validate\HMRC" --disclosureSystem hmrc --xdgConfigHome "C:\Windows\Temp\Arelle" --logFile "C:\A\validationlog.xml" --logFormat "%(message)s - %(file)s" -o "C:\A\renderer_out.zip" --internetConnectivity=online

Could you please help us to check this and do let us know, if there is any workaround to get the renderer output.

Note: If we are trying from GUI using respective Disclosure System (CIPC/HMRC), we are getting valid htm file and the file is opening correctly in ixviewer with all details.

### Documents

for CIPC here is rendererin.zip attached.
[renderer_in.zip](https://github.com/Arelle/Arelle/files/15267324/renderer_in.zip)

### If running from the command line, what command did you run?

"C:\Program Files\Arelle\arelleCmdLine.exe" -f "D:\CIPC_x_9th\renderer_in.zip"    --plugins "EdgarRenderer|validate\cipc" --validate --disclosureSystem cipc  --logFile "D:\CIPC_x_9th\validationlog.xml" --logFormat "%(message)s - %(file)s"  -o "D:\CIPC_x_9th\renderer_out.zip" --internetConnectivity offline

### Interface

CLI (arelleCmdLine)

### Version

2.25.4 , 2.26.7

### Download

GitHub release (bundled Python)

### Operating System

Windows

**Comment by austinmatherne-wk** [comment]
Hi again @anilpatra023,

It appears that you're trying to use the SEC viewer with a non SEC report? As far as I'm aware the SEC doesn't support this scenario. You may want to consider using a general purpose viewer such as the [Arelle viewer](https://github.com/Arelle/ixbrl-viewer) which is intended to support iXBRL filings for all jurisdictions.

The issue you've described pertains to the SEC's ixviewer and EdgarRenderer plugin, which is not maintained within this repository or by the Arelle team. For issues related to the SEC plugins, we kindly ask you to contact the SEC directly.

For your reference, as stated in [our readme](https://github.com/Arelle/Arelle#edgarrenderer-or-efm-validations):
> The SEC develops and maintains the EdgarRenderer and EFM validation plugins. Please report issues with these plugins directly to the SEC (StructuredData@sec.gov).

Kind regards,
Austin Matherne

**Comment by anilpatra023** [comment]
Hi @austinmatherne-w,
We understand that we are using ix-viewer, but that is the main issue. We are not getting the renderer output, which we are getting while we are trying from Arelle GUI i.e. a **out** folder is getting generated for CIPC & HMRC. 
Could you please check on this.

**Comment by austinmatherne-wk** [comment]
The workflow from the GUI isn't performing CIPC or HMRC validation when the viewer is generated.

You could try doing something similar from the command line by separating the validation (cipc disclosure system) and viewer (efm disclosure system) requests.

Generate viewer:
"C:\Program Files\Arelle\arelleCmdLine.exe" -f "D:\CIPC_x_9th\renderer_in.zip" --plugins "EdgarRenderer" --disclosureSystem efm --logFile "D:\CIPC_x_9th\viewerlog.xml" --logFormat "%(message)s - %(file)s" -o "D:\CIPC_x_9th\renderer_out.zip" --internetConnectivity offline

And perform validation:
"C:\Program Files\Arelle\arelleCmdLine.exe" -f "D:\CIPC_x_9th\renderer_in.zip" --plugins "validate\CIPC" --disclosureSystem cipc --logFile "D:\CIPC_x_9th\validationlog.xml" --logFormat "%(message)s - %(file)s" --internetConnectivity offline
