### ISSUE TITLE
collections module import error.

### ISSUE THREAD

**Issue by bhnvx** [Arelle/Arelle#1226]
### What happened?

i use
---
python:3.11.6
arelle:2.2
---

in PythonUtil.py, raised error like `ImportError: cannot import name 'MutableSet' from 'collections'`
in python 3.11.6, `MutableSet` is in collections.abc

and also in pyparsing/pyparsing_py3.py line 627, should be change
`collections.MutableMapping.register(ParseResults)` -> `collections.abc.MutableMapping.register(ParseResults)`

is correct?

### Interface

Python library (pip install)

### Version

Name: arelle-release Version: 2.27.2

### Download

pip install

### Operating System

macOS

**Comment by austinmatherne-wk** [comment]
Hi @bhnvx,

Thanks for reaching out. Both of these issues should be resolved in recent versions of Arelle. Please update to the latest release.

Thanks,
Austin
