### ISSUE TITLE
The --key parameter does not work when launching ValidationModule

### ISSUE THREAD

**Issue by ZuevIlya** [Arelle/Arelle#1409]
### What happened?

Our project uses the ValidateModule application from the command line. Arguments are written to the command line, one of which is --key. As far as I understand, this parameter is calculated from two parts: the time the key was created and the working directory of the module. When the module is launched, our process hangs in the run function in the CntrlCmdLine.py class at this point:
while not access.is_valid():
pass
Apparently, this happens because Arelle creates its own key using the same principle and compares it with ours. But these keys are far from always the same. Our key is created a little earlier than the ValidateModule module is launched. Tell me, what could be the problem? How can I create keys at the same time so that their sha256 hashes match? Or is the problem not in them at all? Thanks in advance
Error log:
^CTraceback (most recent call last):
  File "/home/mi/.local/lib/python3.7/site-packages/cx_Freeze/initscripts/__startup__.py", line 124, in run
  File "/home/mi/.local/lib/python3.7/site-packages/cx_Freeze/initscripts/[console.py](https://console.py/)", line 17, in run
  File "[ValidateModule.py](https://validatemodule.py/)", line 18, in <module>
  File "validatemod/[CntlrCmdLine.py](https://cntlrcmdline.py/)", line 49, in validatemod.CntlrCmdLine.main
  File "validatemod/[CntlrCmdLine.py](https://cntlrcmdline.py/)", line 498, in validatemod.CntlrCmdLine.parseAndRun
  File "validatemod/[CntlrCmdLine.py](https://cntlrcmdline.py/)", line 564, in [validatemod.CntlrCmdLine.CntlrCmdLine.run](https://validatemod.cntlrcmdline.cntlrcmdline.run/)
  File "validatemod/[ValidateFormula.py](https://validateformula.py/)", line 197, in [validatemod.ValidateFormula.Access.is](https://validatemod.validateformula.access.is/)_valid
  File "validatemod/[ValidateFormula.py](https://validateformula.py/)", line 203, in validatemod.ValidateFormula.Access.check_key
KeyboardInterrupt

### If running from the command line, what command did you run?

/home/astra-admin/InitialSetupREDOS/delta-streampped-git/bin/ValidateModule -f /home/astra-admin/InitialSetupREDOS/delta-streampped-git/fileStorage/xbrl/XBRL_1111111111111_ep_issue_document_27_20241101.xml --packages /home/astra-admin/InitialSetupREDOS/delta-streampped-git/fileStorage/taxonomies/dko_txnm_v0.3.5_29102024.zip --key 7deafbb745499e79d69ff75882936f5b809f7792e92af088b1427a290cf39ffd --parameters {http://parameters}refPeriodEnd=2024-11-01,{http://parameters}refPeriodStart=2024-10-31,{http://parameters}DateDoc=2024-11-01 --pre /home/astra-admin/InitialSetupREDOS/delta-streampped-git/fileStorage/temp/cbr-converter-temporary-4698449286478761500.pre.xml --dim /home/astra-admin/InitialSetupREDOS/delta-streampped-git/fileStorage/temp/cbr-converter-temporary-11210059796556121019.dim.xml --formulae /home/astra-admin/InitialSetupREDOS/delta-streampped-git/fileStorage/temp/cbr-converter-temporary-17465638720131219646.formulae.xml --parametersFile /home/astra-admin/InitialSetupREDOS/delta-streampped-git/fileStorage/temp/cbr-converter-temporary-2622246800452689965.parametersFile.xml --refFile /home/astra-admin/InitialSetupREDOS/delta-streampped-git/fileStorage/temp/cbr-converter-temporary-8004331783667799862.refFile.xml --labelRolesFile /home/astra-admin/InitialSetupREDOS/delta-streampped-git/fileStorage/temp/cbr-converter-temporary-7458434410145424980.labelRolesFile.xml --namespacesFile /home/astra-admin/InitialSetupREDOS/delta-streampped-git/fileStorage/temp/cbr-converter-temporary-4548556851420909650.namespacesFile.xml --export --exportDir /home/astra-admin/InitialSetupREDOS/delta-streampped-git/fileStorage/temp/5fbee80b-1698-4fbc-80e6-21343ed4b3bb/ --uiLang ru --labelLang ru-RU --formula none --logFormat "%(messageCode)s DIVIDER %(message)s DIVIDER %(file)s DIVIDER %(refs)s DIVIDER %(levelname)s DIVIDER %(args)s ENDOFROW"

### Interface

CLI (arelleCmdLine)

### Version

Validation Module (r) 64bit 2018-10-19 10:25 UTC

### Download

From source (git checkout)

### Operating System

Linux

**Comment by austinmatherne-wk** [comment]
Hi @ZuevIlya,

Arelle doesn't have a `ValidateModule` or a `--key` argument. Are you using [a tool that has Arelle embedded](https://arelle.readthedocs.io/en/2.35.8/index.html#arelle-within-other-products) within it?

> ## Arelle Within Other Products
> A number of service providers embed Arelle within their XBRL products and tools. If you’re having an issue with Arelle within one of these offerings please contact the developer of that tool for support or first verify that you have the same issue when using Arelle directly. Most issues in these situations are caused by the tool using an old version of Arelle or not running a valid command.

**Comment by ZuevIlya** [comment]
@austinmatherne-wk No, we are using a version of arelle similar to this one: https://github.com/Arelle/Arelle/releases/tag/2.2.4 but older (Verifier(r) 64 bit October 19, 2018 10:25 UTC). In it, the ValidateModule application is replaced by ArelleCmdLine, but the meaning is the same

**Comment by austinmatherne-wk** [comment]
I checked out the repo [from October 19th, 2018](https://github.com/Arelle/Arelle/tree/2edebf283601a365db943f63d76b5eb0468ad32d/) and the --key param didn't exist back then either. Are you perhaps using a fork of Arelle or some non public plugin?

**Comment by ZuevIlya** [comment]
@austinmatherne-wk  Sorry about that. It was our modification, I didn’t know it. Question closed
