### ISSUE TITLE
wrong categorizing in presentation tab 

### ISSUE THREAD

**Issue by mohamadk** [Arelle/Arelle#1432]
### What happened?

When loading apple 10q filing, there is a wrong categorization of items in presentation tab 
https://www.sec.gov/ix?doc=/Archives/edgar/data/320193/000032019324000069/aapl-20240330.htm

![Screenshot 2024-12-04 at 8 54 37 AM](https://github.com/user-attachments/assets/65445a98-ae6b-4b85-9d79-69341fe5a871)
![Screenshot 2024-12-04 at 8 53 16 AM](https://github.com/user-attachments/assets/ed23a40f-30e5-4bf0-9239-9e9f52d1df8c)

as you can see it looks like the Table and Line Items are not the same structure as the report itself 

The Correct table should be 
Net sales:
Cost of sales:
Operating expenses:

and line items should be 
Product
services
 

### If running from the command line, what command did you run?

python -B arelleGUI.pyw 

### Interface

GUI (arelleGUI)

### Version

2.35.9

### Download

GitHub release (bundled Python)

### Operating System

macOS

**Comment by austinmatherne-wk** [comment]
Hi @mohamadk,

The presentation tab is displaying the XBRL concepts as Apple built and ordered them in [their presentation linkbase](https://www.sec.gov/Archives/edgar/data/320193/000032019324000069/aapl-20240330_pre.xml) that they filed with the SEC. There's no requirement that the presentation linkbase matches the display order of the inline report.

**Comment by austinmatherne-wk** [comment]
Unfortunately, the HTML layout isn’t directly part of the XBRL model. While you could manually parse the HTML to recreate it, this isn’t typically practical (HTML structure doesn't always match the rendered layout). Generally, when people want to view the XBRL details as they appear in the HTML, they use an inline viewer like the one you linked to above.
