### ISSUE TITLE
pip install not working on Ubuntu

### ISSUE THREAD

**Issue by Stevod** [Arelle/Arelle#1463]
### What happened?

I have installed arelle-release using 'pip install arelle-release'  in two clean environments but every time I run the controller, I get the error:
(<class 'AttributeError'>, AttributeError("'Cntlr' object has no attribute 'skipDTS'"), <traceback object at 0x7bd89776c680>)

When I look at the debugger, it looks as though this (and other objects in the modelManager) are located a further level down in the hierarchy, as shown in the attached object model (i.e. in self.modelManager.modelManager, not self.modelManager).

Not entirely sure what to do. I tried replacing all instances in the arelle package code with the double reference but that wasn't successful.

Advice would be appreciated as the arelle GUI works successfuly in the same install. I also tried installing by cloning from github but got the same problem.

![arelle_error](https://github.com/user-attachments/assets/b6f1aea1-70e6-438c-a5ab-1e7dc60b6632)

### Interface

Python library (pip install)

### Version

2.36.3

### Download

pip install

### Operating System

Linux

**Comment by Stevod** [comment]
I have modified the method of initiation to below and that seems to have solved the problem :

from arelle import Cntlr
    try:
        # Load the XBRL file into a ModelXbrl instance

        model_xbrl = Cntlr.Cntlr().modelManager.load(xbrl_file)

        # Check if the file was loaded successfully
        if model_xbrl is not None:
            print("XBRL file loaded successfully!")

            # Example: Access some data from the loaded model
            for fact in model_xbrl.facts:
                print(f"Context: {fact.contextID}, Concept: {fact.qname}, Value: {fact.value}")
        else:
            print("Failed to load the XBRL file.")
    except Exception as e:
        print(f"An error occurred: {e}")
    finally:
        # Clean up resources
        if 'model_xbrl' in locals() and model_xbrl is not None:
            model_xbrl.close()

**Comment by austinmatherne-wk** [comment]
Hi @Stevod,

The Cntlr class serves as [a base class](https://github.com/Arelle/Arelle/blob/736a925cc30e2bf811d23b17a8ff99ee4c394eea/arelle/Cntlr.py#L73-L100) designed to be extended (e.g., by CntlrCmdLine, CntlrWinMain, or your own implementation). While it can be used directly for simpler use cases, it tends to be challenging for more advanced operations, such as validation.

I’d recommend checking out [the Session API](https://arelle.readthedocs.io/en/2.36.3/python_api/python_api.html#querying-a-model). It currently wraps CntlrCmdLine, abstracting away the implementation, and will eventually rely on its own Cntlr implementation. This interface is designed to handle everything the CLI can do using arguments but provides a cleaner approach via the Python API and a configuration class.

Let me know if you have any questions!
