### ISSUE TITLE
Banish re

### ISSUE THREAD

**Issue by hermfischer** [Arelle/Arelle#159]
Current imports of regex library are conditional, with fall back to re, because regex didn't exist on older Pythons.

SEC filers running from source code, using dei after 2021q4 and AuditorName AuditorLocation facts (mandatory for annual filings after 2021-12-15) are greeted with schema errors if they didn't install regex because re doesn't support pattern [\p{L}\p{N}].*

Investigate removing conditional regex imports which fallback to re (at least in XmlValidate.py).  Only regex and no re anywhere?

**Comment by sagesmith-wf** [comment]
👍 looks like `re` is really slow
