### ISSUE TITLE
Calling the controller in python directly from the file wants a nonexistent directory

### ISSUE THREAD

**Issue by spooky-ape-butt-42069** [Arelle/Arelle#161]
Since this is the only instructions for the Python API https://arelle.org/arelle/documentation/api/ I've run into issues in creating an instance of the controller (which appears to be required).

I get a strange error when trying to import and instantiate the class directly
```
from arelle import Cntlr
ctlr = Cntlr.Cntlr()
```

`PermissionError: [Errno 13] Permission denied: '/home/nagat'`

It appears to be trying to point to a directory from one of the devs. I cant find the reference in Cntlr.py . Could it be leaking from whomever created the build? There aren't any arguments to specify any directories, so I am not sure what to do.

**Comment by derekgengenbacher-wf** [comment]
When I run your provided commands from the command line in my python environment, they work and I do not get a PermissionsError. @spooky-ape-butt-42069 could you provide some additional information, please, perhaps a stack trace to help us replicate?

**Comment by spooky-ape-butt-42069** [comment]
It's strange. That error was persisting until I performed some plugin reinstalls and it then disappeared never to be seen again, I can't pinpoint what caused it but it's been working well now. Thanks!

**Comment by ggravlingen** [comment]
Although an old issue I'll add to it. I had this issue as well when I installed from pypi. It worked as expected when installing directly from this repo.

**Comment by austinmatherne-wk** [comment]
Hi Patrik. There isn't an official pypi Arelle distribution (yet). There are some older packages floating around pypi, but none of them were packaged and released by the team working on this repo.
