### ISSUE TITLE
Arelle 1.2022.03.22 fails to open any iXBRL Taxonomy Packages

### ISSUE THREAD

**Issue by sachakaelin** [Arelle/Arelle#168]
Dear all,

The latest version of arelle (2022-03-22) seems to fail opening any iXBRL Taxonomy packages.
![grafik](https://user-images.githubusercontent.com/17023528/159434950-e12401dc-3ffe-46ec-90b5-1ed45ff342ab.png)

I tried with ESEF conformance suite 2021 test G2-1-2 (but to me it seems to affect any package).

Message from Arelle is
```
[AttributeError] Unrecoverable error: 'list' object has no attribute 'endswith', abc-2019-12-31.xhtml - abc-2019-12-31.xhtml 
Traceback (most recent call last):
  File "Z:\Users\arelle\hfdev\arelle\ModelDocument.py", line 145, in load
  File "C:\Program Files\Arelle\plugin\validate\ESEF\__init__.py", line 106, in modelXbrlBeforeLoading
    if (modelXbrl.fileSource.selection.endswith(".xml") and
AttributeError: 'list' object has no attribute 'endswith'
[ESEF.3.1.3.missingOrInvalidTaxonomyPackage] RTS Annex III Par 3 and ESEF 3.1.3 requires an XBRL Report Package but one could not be loaded. - 
[ESEF.RTS.Art.6.a.noInlineXbrlTags] RTS on ESEF requires inline XBRL, no facts were reported. - 
not successfully loaded in 0.00 secs
```

Can sombody confirm this issue?

Thanks and best regards,
Sacha

**Comment by derekgengenbacher-wf** [comment]
Hi @sachakaelin. I am reproducing the error as well. We are taking a look.

**Comment by derekgengenbacher-wf** [comment]
This [PR](https://github.com/Arelle/Arelle/pull/169) addresses the issue.

**Comment by derekgengenbacher-wf** [comment]
Once we have this merged we will update the builds.

**Comment by derekgengenbacher-wf** [comment]
A new build has been released.

**Comment by derekgengenbacher-wf** [comment]
Thanks for pointing this out @sachakaelin

**Comment by sachakaelin** [comment]
@derekgengenbacher-wf appreciate your swift response – working as expected.
