### ISSUE TITLE
Incorrect qname property for ModelInlineFact and ModelInlineFootnote

### ISSUE THREAD

**Issue by ChristopheDeBernardi** [Arelle/Arelle#187]
The `ModelInlineFact` and `ModelInlineFootnote` instances have wrong "values" for their `qname` property.

In the case of footnotes, the property returns `XbrlConst.qnLinkFootnote` which is not correct for inline XBRL.

![image](https://user-images.githubusercontent.com/57985290/167109390-5f2ebfdd-01e6-4e55-a8fc-4386c214f4af.png)

For facts the property returns the concept's QName.

![image](https://user-images.githubusercontent.com/57985290/167109927-8280edf4-cc3b-4fb1-ba1b-3da0f5055ac4.png)

**Comment by austinmatherne-wk** [comment]
Hi @ChristopheDeBernardi. The `self.qname` property for inline models in Arelle exposes the extracted XBRL instance model (other parts of Arelle are dependent on this functionality). Does `self.elementQname` provide what you're looking for?

**Comment by austinmatherne-wk** [comment]
If `self.elementQname` doesn't solve this issue for you please let us know.
