### ISSUE TITLE
Arelle installation via pypi

### ISSUE THREAD

**Issue by http203** [Arelle/Arelle#189]
Hello, I noticed that some old Arelle versions are available on **pypi** (https://pypi.org/project/arelle).

Is there any plan to publish Arelle updates on that service?

Thank you!

**Comment by sagesmith-wf** [comment]
@http203, short answer, yes :). We are working on a CI story for this project that you will hopefully see soon that will include a pypi package. Its complicated by the large conformance suits and the multiple OS distributions but will hopefully be available for you and others soon

**Comment by selgamal** [comment]
> @http203, short answer, yes :). We are working on a CI story for this project that you will hopefully see soon that will include a pypi package. Its complicated by the large conformance suits and the multiple OS distributions but will hopefully be available for you and others soon

This is great news!

I have a suggestion, how about a sort of an "interface" that enables access to the installed arelle application from python.

I am implementing something similar for my personal use, I wrote a script that figures out the locations of arelle folders (config, resources...) and adds the necessary entries to python path, when I import that script I have access to import arelle objects in my code from the arelle application already installed on my machine or from source if I point the script to my local project folder (of course all dependencies need to be  installed in my environment for this to work).

The benefit is that I am running from the same arelle version whether I am importing in python or running the app.
 
I think this will be a useful feature to add if it makes sense.

**Comment by sagesmith-wf** [comment]
@selgamal I'm not really sure of the use case for what you are describing. I'm assuming its maybe getting around making the dev environment work properly on your host machine? If that's the use case, we hope to make documentation that helps make that easy for users to avoid the want to use the suggested script. We are hoping to not be a redistribution for TKinter/Python etc. so would appreciate some feedback (perhaps on another issue) on the parts of the dev setup that make it desirable to directly edit the installed application

**Comment by selgamal** [comment]
@sagesmith-wf  yes you are correct I didn't think that through.
Anyway what I understood from your first comment is that you are planning to release a pypi package, if this is the case I will hold this thought until the package is available and make a demo explaining what I meant.
