### ISSUE TITLE
How to specify OIM-CSV Dimensions  has-hypercube with @xbrldt:contextElement="scenario"

### ISSUE THREAD

**Issue by pontsoleil** [Arelle/Arelle#221]
Question

loadFromOIM.py creates a dimension under &lt;segment> by default.
Is there any parameter to specify has-hypercube with @xbrldt:contextElement="scenario"?

XBRL Japan, Nobu

**Comment by pontsoleil** [comment]
I got the following answer from Paul.
<h3>&quot;</h3>
The OIM does not capture the difference between segment and scenario dimensions.  When converting an OIM document (e.g. xBRL-CSV) into the xBRL-XML format, the correct container to use is inferred from the taxonomy, as described in the last part of [xBRL-XML section 3.2](https://www.xbrl.org/Specification/xbrl-xml/REC-2021-10-13/xbrl-xml-REC-2021-10-13.html#sec-dimensions):

When serialising to xBRL-XML, all taxonomy-defined dimensions for all facts in a report are serialised to the same container element (either xbrli:segment or xbrli:scenario ). If the report's DTS contains hypercubes for a single container, then that container is used for all taxonomy-defined dimensions. If the DTS contains hypercubes for both containers, the container should be chosen so as to achieve dimensional validity for all facts, if possible. If this is not possible, the container should be chosen arbitrarily, and appropriate XBRL Dimensions [DIMENSIONS] errors raised. If the report's DTS does not contain any hypercubes, or if dimensional validity can be achieved using either container, xbrli:scenario should be used for all dimensions.

So, assuming your taxonomy only contains hypercubes with contextElement="scenario", then all dimensions will be serialised to <xbrli:scenario>

Arelle shall understand contextElement="scenario", Unfortunately Arelle converted the test OIM-CSV to dimensions within the <segment>, even though the definition link specified xbrldt:contextElement="scenario".  

Pl;ease check https://github.com/pontsoleil/xBRL-Alpha/tree/master/xBRL/OIM-CSV

**Comment by austinmatherne-wk** [comment]
Hi @pontsoleil! Thanks for the bug report. Can you confirm if #232 resolves this issue for you?

**Comment by pontsoleil** [comment]
[austinmatherne-wk](https://github.com/austinmatherne-wk)   
Thank you for your kind answer.  
I'm new to this GitHub. Please let me know where do I download the revised loadFromOIM and / or saveLoadableOIM?

**Comment by austinmatherne-wk** [comment]
I'm happy to help. You can download the updated loadFromOIM.py [here](https://github.com/austinmatherne-wk/Arelle-open/blob/XT-2246/arelle/plugin/loadFromOIM.py)

**Comment by pontsoleil** [comment]
[austinmatherne-wk](https://github.com/austinmatherne-wk)  

Thank you it works as expected.

[oim-example-metadata.xml](https://github.com/pontsoleil/xBRL-Alpha/blob/master/xBRL/OIM-CSV/oim-example-metadata.xml)

```
PS C:\Users\...\GitHub\Arelle> python arelleCmdLine.py --plugins 'loadFromOIM|saveLoadableOIM' -f ../e-invoice/xBRL/OIM-CSV/oim-example-metadata.json --saveOIMinstance ../e-invoice/xBRL/OIM-CSV/oim-example-metadata.xml
[info] Activation of plug-in Load From OIM successful, version 1.2. - loadFromOIM
[info] Activation of plug-in Save Loadable OIM successful, version 1.2. - saveLoadableOIM
[info] loaded in 1.10 secs at 2022-07-20T10:12:13 - C:\Users\nobuy\OneDrive\ドキュメント\GitHub\e-invoice\xBRL\OIM-CSV\oim-example-metadata.json
PS C:\Users\...\GitHub\Arelle>
```
