### ISSUE TITLE
Extract value from roleRef in ESEF report

### ISSUE THREAD

**Issue by ggravlingen** [Arelle/Arelle#225]
Hi,

I'm running version 0.9.91 and have successfully been able to extract facts from an annual report published under the ESEF-format. It would be very helpful to add further context to the facts by including a value found under `roleRef`. The excerpt below is found in a file named `xyz-2021-12-31_cal.xml` and for each fact, I'd like to know if it belongs to the role `ProfitOrLoss`, `StatementOfFinancialPosition` or `StatementOfCashFlows`. Can this be achieved?

```
<roleRef roleURI="http://atlascopco.com/roles/ProfitOrLoss" xlink:href="atla-2021-12-31.xsd#ProfitOrLoss" xlink:type="simple" xmlns:xlink="http://www.w3.org/1999/xlink" />
<roleRef roleURI="http://atlascopco.com/roles/StatementOfFinancialPosition" xlink:href="atla-2021-12-31.xsd#StatementOfFinancialPosition" xlink:type="simple" xmlns:xlink="http://www.w3.org/1999/xlink" />
<roleRef roleURI="http://atlascopco.com/roles/StatementOfCashFlows" xlink:href="atla-2021-12-31.xsd#StatementOfCashFlows" xlink:type="simple" xmlns:xlink="http://www.w3.org/1999/xlink" />
```

**Comment by sagesmith-wf** [comment]
I'm assuming you are running with the actual python code and already have access to a ModelXbrl if you are able to extract the facts. Assuming that's true something like this might work for you:


```java python
from arelle.XbrlConst import summationItem
import json
rel_set = m.relationshipSet(summationItem)
concepts_by_roles = {}
for rel in rel_set.modelRelationships:
    l = concepts_by_roles.get(rel.linkrole, [])
    from_clark = rel.fromModelObject.qname.clarkNotation
    to_clark = rel.toModelObject.qname.clarkNotation
    if from_clark not in l:
        l.append(from_clark)
    if to_clark not in l:
        l.append(to_clark)
    if rel.linkrole not in concepts_by_roles:
        concepts_by_roles[rel.linkrole] = l

print(json.dumps(concepts_by_roles, indent=4))
```

that'll print out all concepts used in a calculation on a per role bases in this form:

```
{
     "role": [
          "conceptA",
           "conceptB"
      ]
}
```

skipping the print, you should be able to use that dict and marry it up to facts based on the fact's `concept.qname.clarknotation`

**Comment by ggravlingen** [comment]
That worked like a charm, thank you very much!
