### ISSUE TITLE
Question regarding the Taxonomy package is not a zip file-error

### ISSUE THREAD

**Issue by ggravlingen** [Arelle/Arelle#236]
While parsing ESEF-files, I'm getting the `Taxonomy package is not a zip file` below. I'm not convinced this is a bug as I note the test suite is based on zip-files, leading me to believe the XBRL-packages are expected to be in that format.

I couldn't get zip-files to work (the `catalog.xml` file wasn't parsed correctly), so I've unzipped and instead load the compressed file's contents. It works as expected so the `Taxonomy package is not a zip file` error is a bit confusing. It's logged [here](https://github.com/Arelle/Arelle/blob/30b48155d7a01d3a2caf3de316d9e1a1d58ed0b2/arelle/PackageManager.py#L479) and then the code proceeds to parse the files.

Wouldn't it make more sense to be silent until the `IOError` error is raised in the end?

I'm also getting the `tpe:invalidMetaDataFile` error in every file but that seems to be due to using [an XSD-file](https://github.com/Arelle/Arelle/blob/30b48155d7a01d3a2caf3de316d9e1a1d58ed0b2/arelle/PackageManager.py#L25) that hasn't been updated at the source for a while.

```
2022-07-21 15:33:39,914 [tpe:invalidArchiveFormat] Taxonomy package is not a zip file. - catalog.xml 

2022-07-21 15:33:39,935 [tpe:invalidMetaDataFile] Taxonomy package file syntax error Element '{urn:oasis:names:tc:entity:xmlns:xml:catalog}catalog': No matching global declaration available for the validation root., line 1 - catalog.xml 

2022-07-21 15:33:39,939 [tpe:invalidArchiveFormat] Taxonomy package is not a zip file. - taxonomyPackage.xml 
```

**Comment by sagesmith-wf** [comment]
I am not following your error 100% are you trying to load an esef filing or the esef taxonomy package? Esef requires a report package (which is basically the same format as the taxonomy package) so it may be firing on that. If you are trying to load the taxonomy package I believe its wanting you to follow this format [spec](https://www.xbrl.org/Specification/taxonomy-package/REC-2016-04-19/taxonomy-package-REC-2016-04-19.html) and [example](https://xbrl.fasb.org/us-gaap/2022/us-gaap-2022.zip). I am assuming you didn't do the meta-inf folder but I don't know for sure.

**Comment by ggravlingen** [comment]
Sorry about the confusion, I'm trying to load an ESEF-filing like so:

```
  with os.scandir(PATH_FILINGS) as dir_iter:
      for idx, entry in enumerate(dir_iter):
          for root, _, files in os.walk(entry.path):
              for file in files:
                  if FILE_ENDING_XML in file:
                      url_filing = os.path.join(root, file)

                  if file in [
                      FileName.TAXONOMY_PACKAGE,
                      FileName.TAXONOMY_PACKAGE_DOT,
                      FileName.CATALOG,
                  ]:
                      url_taxonomy.append(os.path.join(root, file))

          if url_filing is not None and url_taxonomy:
              try:
                  model_manager: ModelManager = ModelManager.initialize(cntlr)
                  model_xbrl: ModelXbrl = model_manager.load(
                      url_filing, taxonomyPackages=url_taxonomy
                  )
                  # additional code to parse facts
```

This is what the folder I'm trying to parse looks like:
![image](https://user-images.githubusercontent.com/21142447/180296339-675fe080-1e58-45cb-b4c3-df239202f6c9.png)

**Comment by austinmatherne-wk** [comment]
What are `url_filing` and `url_taxonomy` equal to when passed to `model_manager.load()`?

**Comment by ggravlingen** [comment]
> What are `url_filing` and `url_taxonomy` equal to when passed to `model_manager.load()`?

```
url_filing => /filings/549300BMPLK5HJNB0O54-2021-12-31-sv/reports/549300BMPLK5HJNB0O54-2021-12-31-sv.xhtml

url_taxonomy => ['/filings/549300BMPLK5HJNB0O54-2021-12-31-sv/META-INF/catalog.xml', '/filings/549300BMPLK5HJNB0O54-2021-12-31-sv/META-INF/taxonomyPackage.xml']
```

> 
> But to partially answer your question, a taxonomy package [must be a zip](https://www.xbrl.org/Specification/taxonomy-package/REC-2016-04-19/taxonomy-package-REC-2016-04-19.html#term-taxonomy-package) and the `tpe:invalidArchiveFormat` error should be raised if it's not.
> 
> > A [Taxonomy Package](https://www.xbrl.org/Specification/taxonomy-package/REC-2016-04-19/taxonomy-package-REC-2016-04-19.html#term-taxonomy-package) MUST conform to the .ZIP File Format Specification [[ZIP]](https://www.xbrl.org/Specification/taxonomy-package/REC-2016-04-19/taxonomy-package-REC-2016-04-19.html#ZIP) (tpe:invalidArchiveFormat).

Thanks, then it's an implementation error on my side. I tried loading the zip-file directly and remembered why I went for extracting and then loading the extracted files:

This code:
```
def read_and_save_filings_v2():
    """Test."""
    cntlr = Controller()
    model_manager: ModelManager = ModelManager.initialize(cntlr)
    model_xbrl: ModelXbrl = model_manager.load(
        f"{PATH_ARCHIVES}/529900G9LZILBPCZXA17-2021-12-31-sv.zip",
    )
    print(model_xbrl)
```

Yielded this error:
```
2022-07-22 08:00:53,055 [IOerror] 529900G9LZILBPCZXA17-2021-12-31-sv.zip: file error: 'utf-8' codec can't decode byte 0xa2 in position 11: invalid start byte - 529900G9LZILBPCZXA17-2021-12-31-sv.zip
```

It might be something wrong with the zip-file but I can't figure out what it is as extracting it using Python's `zipfile` module works. Is this something you've seen in the past?

**Comment by austinmatherne-wk** [comment]
I haven't. It *should* be reading the zip as bytes and decoding the files within when they're accessed. So the encoding issue makes more sense from reading a file out of the zip, but it's hard to tell based on that error.

My guess is the encoding of one of the files in the zip doesn't match the XML encoding declaration. Adding more logging to `FileSource` might help. I'd start by seeing if [this](https://github.com/Arelle/Arelle/blob/165a725fb1d8aaa4b841631b427a94178f3330a8/arelle/FileSource.py#L167) is throwing an exception.

**Comment by ggravlingen** [comment]
> I haven't. It _should_ be reading the zip as bytes and decoding the files within when they're accessed. So the encoding issue makes more sense from reading a file out of the zip, but it's hard to tell based on that error.
> 
> My guess is the encoding of one of the files in the zip doesn't match the XML encoding declaration. Adding more logging to `FileSource` might help. I'd start by seeing if [this](https://github.com/Arelle/Arelle/blob/165a725fb1d8aaa4b841631b427a94178f3330a8/arelle/FileSource.py#L167) is throwing an exception.

I've dug into this a bit more and the zip-file in itself is compressed with PK Zip which Python should be able to handle. I suspect the reason an encoding file is thrown is that Arelle for some reason does not consider the file to be a zip and tries to parse it using the `XMLStreamHandler`.

This is the path travelled when executing the code:

- https://github.com/Arelle/Arelle/blob/165a725fb1d8aaa4b841631b427a94178f3330a8/arelle/ModelManager.py#L157
- https://github.com/Arelle/Arelle/blob/165a725fb1d8aaa4b841631b427a94178f3330a8/arelle/ModelXbrl.py#L58 (here, `url=/workspaces/pyesef/pyesef/../archives/529900G9LZILBPCZXA17-2021-12-31-sv.zip`
- https://github.com/Arelle/Arelle/blob/165a725fb1d8aaa4b841631b427a94178f3330a8/arelle/ModelXbrl.py#L71
- https://github.com/Arelle/Arelle/blob/165a725fb1d8aaa4b841631b427a94178f3330a8/arelle/ModelDocument.py#L156
- https://github.com/Arelle/Arelle/blob/165a725fb1d8aaa4b841631b427a94178f3330a8/arelle/FileSource.py#L407 (here, `archiveFileSource` is `None`)
- https://github.com/Arelle/Arelle/blob/165a725fb1d8aaa4b841631b427a94178f3330a8/arelle/FileSource.py#L506 (at this point, I believe we are not where we would expect given that I'm trying to read a Zip-file)

Digging further into why `archiveFileSource` is `None`, I note that this variable is `None`: https://github.com/Arelle/Arelle/blob/165a725fb1d8aaa4b841631b427a94178f3330a8/arelle/FileSource.py#L388

Further, there is one oddity in [this function](https://github.com/Arelle/Arelle/blob/165a725fb1d8aaa4b841631b427a94178f3330a8/arelle/FileSource.py#L53
). The tuple `archivePathSeparators` looks like so: `('.zip/', '.tar.gz/', '.eis/', '.xml/', '.xfd/', '.frm/', '.taxonomyPackage.xml/')` I'm aware that Windows treats zip-files like native folders. Does it work the same way in Linux? Wouldn't we expect `.zip` (without a trailing slash) to be in the tuple?

**Comment by ggravlingen** [comment]
I've might have figured it out by digging through the command line file. I'll post an update when I've got it fully working.

**Comment by ggravlingen** [comment]
Yes, it works to load zip-files by using the mechanisms in the command line file.
