### ISSUE TITLE
Validation performance issues with duplicated facts

### ISSUE THREAD

**Issue by RobinetDenisAcsone** [Arelle/Arelle#242]
There are some performance issues when validating with duplicated facts.

Step to reproduce:
* Add the CBSO taxonomy package (in annex)
* Open the xbrl file (in annex)
* Validate

It can be tested with the rule oa_06.05.1_0009 for example.

From my analysis, it's linked to https://github.com/Arelle/Arelle/blob/master/arelle/FormulaEvaluator.py#L1300, which at the end will make a loop over 1 953 158 evaluationResults here: https://github.com/Arelle/Arelle/blob/master/arelle/FormulaEvaluator.py#L437
Removing duplicate will reduce this list to 29.
Only 31 duplicated facts are removed between the 2 instances.

Note that the problem of the duplication of fact is in an external tools, and not linked to arelle, only the validation is impacted, 

Taxonomy: [nbb-cbso-22.18.19.zip](https://github.com/Arelle/Arelle/files/9218463/nbb-cbso-22.18.19.zip)
Report with duplicate: [report_duplicate.zip](https://github.com/Arelle/Arelle/files/9218486/report_duplicate.zip)
Report without duplicate: [report_without_duplicate.zip](https://github.com/Arelle/Arelle/files/9218487/report_without_duplicate.zip)

It may be linked to https://github.com/Arelle/Arelle/issues/217 since it's performance related.

Tested on current master (55cb2caa4177cac928f51bb41b1df853888b206e)

**Comment by austinmatherne-wk** [comment]
Thank you for reporting @RobinetDenisAcsone. We'll make sure this is looked into as part of the formula performance analysis.

**Comment by austinmatherne-wk** [comment]
As of the latest release of Arelle 2.5.8 we've managed to cut the formula execution time for this taxonomy by about 30%. That's likely as fast as we can get at the moment given the current platform limitations (Python). We have some longer term plans that could potentially close the gap.
