### ISSUE TITLE
Attribute error for ESEF validation

### ISSUE THREAD

**Issue by alexdejong1723** [Arelle/Arelle#279]
In the since the July 2022 version I get the following error message when trying to validate an ESEF reporting package: 

[AttributeError] [Exception] Failed to complete request: 'ModelXbrl' object has no attribute 'validateESEFplugin' [' File "Z:\\Users\\arelle\\devpub\\arelle\\CntlrCmdLine.py", line 1027, in run\n', ' File "Z:\\Users\\arelle\\devpub\\arelle\\ValidateFormula.py", line 990, in validate\n', ' File "C:\\InspectorFiles\\Validation\\Arelle\\plugin\\validate\\ESEF\\__init__.py", line 1105, in validateFormulaFinished\n if not (val.validateESEFplugin):\n']

This error only occurs when using the CI and using the "validate/ESEF" plugin. If I use the GUI I don't get this error. Because of the error, I think the GUI shows an ESEF error where the CI doesn't.

**Comment by austinmatherne-wk** [comment]
Hi @alexdejong1723, I'll look into this. Are you running Arelle from the windows installer downloaded from [arelle.org](https://arelle.org/arelle/pub/)?

**Comment by alexdejong1723** [comment]
Hi Austin,

Indeed. It's the latest Windows version from the website.

Met vriendelijke groet / Best regards,

***@***.***
***@***.******@***.***
***@***.***
Alex de Jong
Product Manager


+31 85 401 54 23 | +31 6 4204 5590
https://parseport.com<https://parseport.com/>
Europalaan 400, 3526 KS, Utrecht, Netherlands
***@***.***

***@***.******@***.***
***@***.***
NOTICE: This email and any attachments may contain confidential information. If you are not the intended recipient, please notify us immediately and then delete this email and all attachments without keeping a copy or disclosing the contents to any other person. Any inbound emails received by ParsePort may be kept for up to five years. According to GDPR you have the right to "be forgotten", so please don't hesitate to contact us if you wish to have your information deleted.
- We Make ESEF Reporting Simple
***@***.***<https://software.xbrl.org/create/parseport-parseport-xbrl-converter>


Van: Austin M. Matherne ***@***.***>
Verzonden: dinsdag 16 augustus 2022 17:27
Aan: Arelle/Arelle ***@***.***>
CC: Alex de Jong ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [Arelle/Arelle] Attribute error for ESEF validation (Issue #279)


Hi @alexdejong1723<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Falexdejong1723&data=05%7C01%7Caj%40parseport.com%7Ce21703cb85c9451b342308da7f9bc5ea%7C1c752242f6e54167b3542deda924b318%7C0%7C0%7C637962604271460055%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=3c9jyCOZDpO5IdP2nvvFFXo2ysT%2FzPbPNZS3mdpk5Jo%3D&reserved=0>, I'll look into this. Are you running Arelle from the windows installer downloaded from arelle.org<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Farelle.org%2Farelle%2Fpub%2F&data=05%7C01%7Caj%40parseport.com%7Ce21703cb85c9451b342308da7f9bc5ea%7C1c752242f6e54167b3542deda924b318%7C0%7C0%7C637962604271615845%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=GpUF2ry7OZZygnwR90ymwbmAs3XYG1JtoNY8GHnMkV0%3D&reserved=0>?

-

**Comment by austinmatherne-wk** [comment]
I'm having trouble replicating this from a clean VM with Arelle 2022.08.08. Can you send me the exact command you're running for the CI?

**Comment by vivet** [comment]
FYI This is also an issue on Linux

**Comment by selgamal** [comment]
@vivet @austinmatherne-wk 
__Not__ getting the mentioned error either, I am using `debian 10`,  `Arelle(r) 1.2022.08.15 (64bit)` . 
Tried the following command:
```bash
arelleCmdLine -f https://filings.xbrl.org/52990018KGR3ILFDNJ20/2022-05-31/ESEF/DK/0/52990018KGR3ILFDNJ20-2022-05-31-en.zip --plugin "inlineXbrlDocumentSet|validate/ESEF" -v --disclosureSystem esef
```

**Comment by alexdejong1723** [comment]
I think I caused some confusion, sorry for that. The errormessage is not seen directly in the command window, but is part of the profilestats in the xml log file.

**Comment by selgamal** [comment]
@alexdejong1723  still can't find it, this is my log file (it is an xml file, .txt just to be able to attach it here)
[mylog.txt](https://github.com/Arelle/Arelle/files/9462057/mylog.txt)

Does this happen with a sepcific filing? I am curious because I been doing some research on the ESEF filings published on XBRL.org and I have n't seen this error before, maybe I am missing something...

**Comment by alexdejong1723** [comment]
I think I figured out the issue. We used " formula=run" in the commandline. When removing that, the issue is gone.
