### ISSUE TITLE
Mac GUI crashes upon load Table Linkbase

### ISSUE THREAD

**Issue by nicky-de-boer** [Arelle/Arelle#280]
Mac OS App version: 2022-08-08

Tried to load the following table linkbase into the Mac App:
EIOPA_SolvencyII_XBRL_Taxonomy_2.8.0/eiopa.europa.eu/eu/xbrl/s2md/fws/solvency/solvency2/2023-07-15/tab/e.02.01.16.01/e.02.01.16.01.xsd.

After loading the GUI crashes (no error message).

I cloned the Arelle repository (master branch) and ran the runMacGUI.sh with environment variable: TKTABLE_LIBRARY=/Arelle/libs/macos/Tktable2.11.
Afterwards loaded the same table linkbase which causes no errors in the local Mac GUI. 

Could you please look into the downloadable mac distribution?
In case of any questions please let me know.

**Comment by austinmatherne-wk** [comment]
Hi @nicky-de-boer. Thanks for reporting.

Right now we have two build processes. There are manually built distributions that are uploaded to arelle.org (this has been the build process for many years) and we recently started producing automated builds that should reduce issues like this. 

Can you try using the [new CI automated build for mac](https://github.com/Arelle/Arelle/actions/runs/2869170894) and see if that handles your use case?

Note, there's a known issue with the automated mac build (#271) that requires removing extended attributes (`sudo xattr -cr /Applications/Arelle.app`) before running it. We're working on resolving this.

**Comment by austinmatherne-wk** [comment]
@nicky-de-boer if you're still having issues even when using the CI build please let us know. Thanks!
