### ISSUE TITLE
Repo Badges

### ISSUE THREAD

**Issue by sagesmith-wf** [Arelle/Arelle#294]
Lots of popular open-source repos maintain a set of badges in the readme that can kind of direct people at a glance to things like required language versions, open issues, builds, versions, supported os, license, ect. Examples of some that are applicable here are:

- ![GitHub Actions](https://img.shields.io/badge/github%20actions-%232671E5.svg?style=for-the-badge&logo=githubactions&logoColor=white)
- ![Python](https://img.shields.io/badge/python-3670A0?style=for-the-badge&logo=python&logoColor=ffdd54)
- ![macOS](https://img.shields.io/badge/mac%20os-000000?style=for-the-badge&logo=macos&logoColor=F0F0F0)
- ![Red Hat](https://img.shields.io/badge/Red%20Hat-EE0000?style=for-the-badge&logo=redhat&logoColor=white)
- ![Ubuntu](https://img.shields.io/badge/Ubuntu-E95420?style=for-the-badge&logo=ubuntu&logoColor=white)
- ![Windows](https://img.shields.io/badge/Windows-0078D6?style=for-the-badge&logo=windows&logoColor=white)
- [![License](https://img.shields.io/badge/License-Apache_2.0-blue.svg)](https://opensource.org/licenses/Apache-2.0)
- ![PyPI](https://img.shields.io/pypi/v/arelle)

There are bunch of cool ones you can make [here](https://shields.io/) showing status on build, tag, ect.

**Comment by ggravlingen** [comment]
Maybe use Arelle's logo for the GitHub organization Avatar too?
