### ISSUE TITLE
XmlUtil.innerText() nested span element whitespace

### ISSUE THREAD

**Issue by hermfischer-wf** [Arelle/Arelle#312]
Problem:  the ixt-sec:durwords transform is not raising an error for: 

```<ix:nonNumeric contextRef="c" format="ixt-sec:durwordsen" name="foo:bar" id="f1">5<span style="letter-spacing:-0.7pt;"> </span>years</ix:nonNumeric>```

The <span> element's inner text should not retain whitespace in this case.

(It would require ```<span style="letter-spacing:-0.7pt;">&#xA0;</span>``` to work properly.  Adding white-space: pre; to the span style with a space character doesn't seem to work in other products.)

Related issue:  ESEF text block discussions on XBRL.EU's BPTG calls.

References: [mozilla](https://developer.mozilla.org/en-US/docs/Web/API/Document_Object_Model/Whitespace)  [W3C](https://www.w3.org/TR/css-text-3/#white-space-processing)

**Comment by brettkail-wk** [comment]
> The element's inner text should not retain whitespace in this case.

I think it should retain.  iXBRL says to concatenate all the text (11.1 [says](https://www.xbrl.org/specification/inlinexbrl-part1/rec-2013-11-18/inlinexbrl-part1-rec-2013-11-18.html#d1e6002) `{value}` is "the concatenation in document order of all descendant text nodes").  The references to mozilla/W3C are only describing the rendering behavior of nodes, which seems unrelated to the DOM behavior ([this](https://html.spec.whatwg.org/multipage/dom.html#the-innertext-idl-attribute) links [this](https://dom.spec.whatwg.org/#concept-descendant-text-content), which says basically the same as iXBRL).

**Comment by hermfischer-wf** [comment]
Agree with the literal reading of  iXBRL spec 11.1.  

Paul Warren also agrees.

This means the bug is in EDGAR ix validator, which is dropping <span style="letter-spacing:-0.7pt;"> </span> enclosed whitespace in transforms.
