### ISSUE TITLE
Incorrect release number from pip build

### ISSUE THREAD

**Issue by davidtauriello** [Arelle/Arelle#336]
### What happened?

When I use `pip install git+https://git@github.com/arelle/arelle.git@master#egg=Arelle-release` I get the right commit, but the wrong build number

![image](https://user-images.githubusercontent.com/11542574/190265624-528faeaa-3433-4666-9228-58ac29f7aedb.png)

![image](https://user-images.githubusercontent.com/11542574/190265803-301546ad-d4e4-4c09-afaa-0f0c68b3a45e.png)

Please let me know if there's a different command I should be using to install Arelle.

FWIW, unsure on the OS question; this is a Jupyter notebook - platform.uname() is system='Linux' version='#202-Ubuntu SMP Thu Aug 4 01:49:29 UTC 2022', machine='x86_64'

### If running from the command line, what command did you run?

pip install git+https://git@github.com/arelle/arelle.git@master#egg=Arelle-release

### Interface

Python library (pip install)

### Version

964f5b13e4e6c999a4f48f61733809a86277cd27 <> 2020.05.10 (does it?)

### Download

pip install

### Operating System

Linux (Ubuntu 20.04)

**Comment by davidtauriello** [comment]
thanks @austinmatherne-wk

Sometime in the last 4 days, it seems like the commits on the master branch no longer install arelle from pip. 

When I try to run !arelle -a I get `bin/bash: arelle: command not found`  although if I ls -l the files are in the proper place.

Any ideas what I might be doing wrong to invoke Arelle?

![image](https://user-images.githubusercontent.com/11542574/191368417-cce2b59b-22b0-4fa5-840e-8c7413dfee06.png)

**Comment by austinmatherne-wk** [comment]
`arelle` and `arelle-gui` were temporarily available as scripts. `arelleCmdLine` [should work](https://github.com/Arelle/Arelle/blob/79513a89efe2d526a05f80ee4a12d09793fd5179/pyproject.toml#L58).

We changed the name to stay consistent with the command that's used when running from source:
`python -m arelleCmdLine`

**Comment by davidtauriello** [comment]
thanks, again @austinmatherne-wk 

last question - in order to use SEC transformation plugin, I found I also needed to copy the config and plugin directories into the build _after_ pip installed from master.  **Is this now the expected behavior for everything beyond the core Arelle processor?**

**Comment by selgamal** [comment]
@davidtauriello you can point arelle to the config folder you like to use using option  `--xdgConfigHome` or setting environment variable `XDG_CONFIG_HOME`, arelle will use the existing config and cache in that locations.

**Comment by austinmatherne-wk** [comment]
I think David is referring to the config and plugin directories from the repo. Those should be included, but I suspect they got dropped during the pyproject.toml conversion. The git integration for managing versions which we'll be switching to shortly also handles  "data files".

David, can you verify that installing from this branch includes those two directories for you?
`pip install git+https://github.com/austinmatherne-wk/Arelle.git@setuptools-scm`

**Comment by davidtauriello** [comment]
hi @selgamal - thanks for the information.

@austinmatherne-wk - I’m confirming the build in your Arelle fork and branch has the missing directories.  I guess these will be restored when the version number issue is resolved - is this correct?

**Comment by selgamal** [comment]
appologies, I thought it had to do with the config and cache folder. but yes installing from master does not include the plugin and the config folder.
installing using `git+https://github.com/austinmatherne-wk/Arelle.git@setuptools-scm` includes both folders.

**Comment by austinmatherne-wk** [comment]
@davidtauriello yes. Our team will be working on version handling next week. I'll make sure the fix for this is prioritized.

**Comment by davidtauriello** [comment]
@austinmatherne-wk - no worries; thanks, again, for your quick responses and help.

**Comment by austinmatherne-wk** [comment]
We published an [arelle release to PyPI](https://pypi.org/project/arelle-release/) (`pip install arelle-release`). The version and packaging issues mentioned here should be resolved.

**Comment by davidtauriello** [comment]
Thanks for your work & help to move Arelle forward, @austinmatherne-wk & development team; pip install is working as expected.
