### ISSUE TITLE
Handle semver versions in Updater.py

### ISSUE THREAD

**Issue by austinmatherne-wk** [Arelle/Arelle#361]
### What should we change and why?

In preparation for switching to semver we need the Updater module [to handle](https://github.com/Arelle/Arelle/blob/f9c8b213ce2409367ee7591be46946775524254d/arelle/Updater.py#L112) semver versions along with the existing versioning by date.

The updater should handle date based versions and semver based versions for both checking the running version and when parsing the version for potential updates. All date based versions should be considered older than any semver versions. 

Note: semver will be handled by setuptools_scm (#364) which has [a versioning scheme](https://github.com/pypa/setuptools_scm/#default-versioning-scheme) for non released versions (distance from last tagged released). The updater shouldn't throw an exception when running from source and an untagged release.

If the current version is a git hash or `0.0.0` then the user is running from source and updates should be ignored.

**Comment by ggravlingen** [comment]
Would a bump of the library to 2.0.0 and using this library be of help here? https://github.com/ludeeus/awesomeversion

**Comment by austinmatherne-wk** [comment]
The plan is to tag a 2.0.0 release after #365 is completed (this week). I'll take a look at the library, but may just stick with parsing with a regex since we control the versions and know what format they'll be in.

**Comment by ggravlingen** [comment]
Yeah, just had a look at the PR you're working on and probably no need for that lib.
