### ISSUE TITLE
Document new usage options in INSTALLATION.md 

### ISSUE THREAD

**Issue by austinmatherne-wk** [Arelle/Arelle#385]
### What should we change and why?

INSTALLATION.md should describe the new ways of installing and using Arelle.
* PyPI package (`pip install arelle-release`)
* Frozen OS builds [attached to](https://github.com/Arelle/Arelle/releases/tag/2.0.0) GitHub releases

**Comment by ggravlingen** [comment]
Great work @austinmatherne-wk and team of getting this up on pypi!

**Comment by selgamal** [comment]
Great work! 
Links  [Arelle Install Guid](https://pypi.org/project/arelle-release/INSTALLATION.md/)  and [contribution guidelines](https://pypi.org/project/arelle-release/CONTRIBUTING.md) on pypi are not working.

**Comment by austinmatherne-wk** [comment]
Thanks guys. We wouldn't have this released yet without all of the help both of you (and everyone else in the community) has provided.

**Comment by ajmed** [comment]
The installation section of the README is an awesome start, and nice work getting the package published to PyPI.

Any chance someone could write some usage instructions? For example, a section on importing Arelle into another python script and running some functions?

Currently I have Arelle packaged alongside my python script and call it like, but it's less than ideal:
```python
xbrl_file = f"/tmp/{accession_number}-xbrl.zip"
cmd = [
    "./arelleCmdLine",
    "--plugin", "xbrlDB|EdgarRenderer",
    "-f", xbrl_file,
    "--disclosureSystem", "efm-pragmatic-all-years",
    "--store-to-XBRL-DB", "database-host,5432,postgres,my-password,mydb,60,postgres",
]
subprocess.run(cmd, stdout=arelle_stdout_file_handle, stderr=arelle_stderr_file_handle, check=False)
```

It would be nice if you showed us an example of installing through PyPI, importing Arelle, and calling a function that does something like the above example.

**Comment by ggravlingen** [comment]
> The installation section of the README is an awesome start, and nice work getting the package published to PyPI.
> 
> 
> 
> Any chance someone could write some usage instructions? For example, a section on importing Arelle into another python script and running some functions?
> 
> 
> 
> Currently I have Arelle packaged alongside my python script and call it like, but it's less than ideal:
> 
> ```python
> 
> xbrl_file = f"/tmp/{accession_number}-xbrl.zip"
> 
> cmd = [
> 
>     "./arelleCmdLine",
> 
>     "--plugin", "xbrlDB|EdgarRenderer",
> 
>     "-f", xbrl_file,
> 
>     "--disclosureSystem", "efm-pragmatic-all-years",
> 
>     "--store-to-XBRL-DB", "database-host,5432,postgres,my-password,mydb,60,postgres",
> 
> ]
> 
> subprocess.run(cmd, stdout=arelle_stdout_file_handle, stderr=arelle_stderr_file_handle, check=False)
> 
> ```
> 
> 
> 
> It would be nice if you showed us an example of installing through PyPI, importing Arelle, and calling a function that does something like the above example.

I've written a wrapper for reading ESEF filings without using the command line. Maybe you can copy some of the logic and use for your own purposes? The code is here:

https://github.com/ggravlingen/pyesef/blob/main/pyesef/helpers/read_and_save_filings.py

**Comment by ajmed** [comment]
@ggravlingen Thanks! I'll pour over this example the next couple days to see what I can make of it. The _extract_model_roles functions looks particularly useful.
