### ISSUE TITLE
[IOerror] file error: [Errno 22] on Windows when loading ESEF filing zip archive using http url 

### ISSUE THREAD

**Issue by selgamal** [Arelle/Arelle#413]
### What happened?

When trying to run ESEF filing from http url on `Windows`:
```shell
# This returns [IOerror]
python arelleCmdLine.py -f https://filings.xbrl.org/5299004SWFL5JAN4W830/2022-06-30/ESEF/DK/0/5299004SWFL5JAN4W830-2022-06-30-en.zip --plugin inlineXbrlDocumentSet
```
I am getting the following message:
```
[IOerror] 5299004SWFL5JAN4W830-2022-06-30.xsd: file error: [Errno 22] Invalid argument: 'D:\\final\\arelle_src\\https:\\filings.xbrl.org\\5299004SWFL5JAN4W830\\2022-06-30\\ESEF\\DK\\0\\5299004SWFL5JAN4W830-2022-06-30-en.zip\\5299004SWFL5JAN4W830-2022-06-30-en\\xbrl.bioporto.com\\2022-06-30\\5299004SWFL5JAN4W830-2022-06-30.xsd' - https://filings.xbrl.org/5299004SWFL5JAN4W830/2022-06-30/ESEF/DK/0/5299004SWFL5JAN4W830-2022-06-30-en.zip/5299004SWFL5JAN4W830-2022-06-30-en/reports/5299004SWFL5JAN4W830-2022-06-30-en.xhtml 3041
```
Also see unit test [here](https://github.com/Arelle/Arelle/actions/runs/3229503076/jobs/5286879883#step:5:94) for the same error.
If I download the file and run from local disk, runs fine:
```shell
# this runs OK
python arelleCmdLine.py -f "C:\Users\Sherif\Desktop\5299004SWFL5JAN4W830-2022-06-30-en.zip" --plugin inlineXbrlDocumentSet
```
Downloading Filing from SEC runs fine, the below command runs fine:
```shell
# this runs OK
python arelleCmdLine.py -f https://www.sec.gov/Archives/edgar/data/789019/000156459021020891/0001564590-21-020891-xbrl.zip --plugin "inlineXbrlDocumentSet|transforms/SEC"
```
Something goes wrong in mapping in PackageManager at this [line](https://github.com/Arelle/Arelle/blob/7765c1ac2a8fd6e939056ae6f0f6ab993e2991ef/arelle/PackageManager.py#L199), it the url fails `isHttp` for some reason and returns the `D:\\final\\arelle_src\\https:\\filings.xbrl.org\\...`, I couldn't figure out what is going on.
This is only in windows.

### Result `--diagnostic` (Running from source)
'arch': 'AMD64',
 'arelle_version': '3552094fbf01a93027b14a0157fde7eb4e37d16f',
 'args': ['arelleCmdLine.py', '--diagnostic'],
 'docker': False,
 'os_name': 'Windows',
 'os_version': '10',
 'python_branch': 'tags/v3.9.9',
 'python_compiler': 'MSC v.1929 64 bit (AMD64)',
 'python_implementation': 'CPython',
 'python_version': '3.9.9',
 'python_virtualenv': True

### If running from the command line, what command did you run?

python arelleCmdLine.py -f https://filings.xbrl.org/5299004SWFL5JAN4W830/2022-06-30/ESEF/DK/0/5299004SWFL5JAN4W830-2022-06-30-en.zip --plugin inlineXbrlDocumentSet

### Interface

CLI (arelleCmdLine)

### Version

3552094fbf01a93027b14a0157fde7eb4e37d16f

### Download

From source (git checkout)

### Operating System

Windows 10

**Comment by austinmatherne-wk** [comment]
@selgamal thank you for reporting! Can you check if #442 resolves this for you?

**Comment by selgamal** [comment]
@austinmatherne-wk Yes, tested on windows using same command and filing loads without error. Thank you!
