### ISSUE TITLE
Fact table returns English cost center although the XML is download in German

### ISSUE THREAD

**Issue by shangguan9191** [Arelle/Arelle#479]
### What happened?

i am trying to read balance sheet in German stock market, however i got still result though i have the German Taxtomoy.

### Documents

![image](https://user-images.githubusercontent.com/64595972/201101167-c890dfb1-d213-4391-8dbd-b653ba76636c.png)

### Interface

Python library (pip install)

### Version

git clone

### Download

GitHub release (bundled Python)

### Operating System

Windows 11

**Comment by shangguan9191** [comment]
Is there any language setting by Arelle

**Comment by austinmatherne-wk** [comment]
Hi @shangguan9191.

Yes, there's a [locale module](https://github.com/Arelle/Arelle/blob/master/arelle/Locale.py) that's configured based on the [cntlr `uiLang` param](https://github.com/Arelle/Arelle/blob/ca4b7693868ccfaf33820cac7e546f78543ff4ef/arelle/Cntlr.py#L143).

**Comment by austinmatherne-wk** [comment]
Closing based on inactivity. Please reach out if you're still having issues with Arelle.
