### ISSUE TITLE
Arelle alters the `LC_ALL` environment variable, affecting other processes

### ISSUE THREAD

**Issue by zaneselvans** [Arelle/Arelle#505]
### What happened?

We use Arelle to extract Federal Energy Regulatory Commission filings distributed in XBRL format, and turn them into a relational database covering many utilities across multiple filing periods. (See e.g. [the 2021 FERC Form 1](https://data.catalyst.coop/ferc1_xbrl)) and our [FERC XBRL Extractor repo](https://github.com/catalyst-cooperative/ferc-xbrl-extractor).

This extraction is an early step in a longer ETL pipeline, and it runs successfully. However, later on in the pipeline, we encounter `UnicodeDecodeError` on some platforms but not others. These errors go away when a single line is commented out in `arelle/Locale.py`. See [this commit](https://github.com/catalyst-cooperative/Arelle/commit/cef2d830e229ae5c5577ac426acf04dd8a40b0a6) in our fork of the Arelle repo from earlier this year.

That line appears to correspond to [line 77 in Locale.py today](https://github.com/Arelle/Arelle/blob/776c34e578f64299a94adc3b1868511c22f7cac3/arelle/Locale.py#L77).

Testing earlier today with v2.2.2 of Arelle rather than our fork, the exact same problem still arises. See [this comment](https://github.com/catalyst-cooperative/ferc-xbrl-extractor/issues/36#issuecomment-1342764869). The exact ultimate error is:

```
    def decode(self, input, final=False):
>       return codecs.ascii_decode(input, self.errors)[0]
E       UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 7113: ordinal not in range(128)
```

The XBRL inputs that were being processed by Arelle are contained in [this zipfile](https://zenodo.org/record/7314437/files/ferc1-xbrl-2021.zip?download=1) which is part of [this FERC Form 1 data archive on Zenodo](https://zenodo.org/record/7314437).

To work around this issue without needing to use a fork of Arelle, @zschira created a context manager that resets the `LC_ALL` environment variable after Arelle is finished running. See [this commit](https://github.com/catalyst-cooperative/ferc-xbrl-extractor/pull/42/commits/54d18d2d31a788dbd7d65298c001cc712e4d14a7):

```py
class ArelleInterface:
    """Clear LC_ALL after Arelle has set it internally.
    Arelle sets LC_ALL by default, which can cause some
    downstream encoding issues. This context manager will
    make sure it is cleared before this becomes a problem.
    """

    def __enter__(self):
        """Do nothing."""
        return self

    def __exit__(self, *exc):
        """Unset LC_ALL and return."""
        locale.setlocale(locale.LC_ALL, "")
        return False


def load_xbrl(path: str | FileSource.FileSource):
    """Load XBRL (either taxonomy or individual filing).
    Args:
        path: URL or local path pointing to an XBRL taxonomy or instance.
    """
    with ArelleInterface():
        cntlr = Cntlr.Cntlr()
        cntlr.startLogging(logFileName="logToPrint")
        model_manager = ModelManager.initialize(cntlr)
        return ModelXbrl.load(model_manager, path)
```

We've experienced this problem on:
* Ubuntu Linux 20.04 (GitHub runners)
* MacOS 13.0.1 (Ventura)

## What was expected?

We expected that Arelle would not result in any persistent side-effects altering the computational environment it and subsequent processes were running in.

### Interface

Python library (pip install)

### Version

version 2.2.2

### Download

pip install

### Operating System

macOS 13 Ventura

**Comment by brettkail-wk** [comment]
It would be nice if Arelle didn't need to change the locale, but it would also be good if addfips explicitly declared the encoding of its files rather than using the system locale.  I'm able to reproduce the problem with a small addfips program, and changing [this line](https://github.com/fitnr/addfips/blob/2d3fb46e6f68343cfa242f812f6b0d83387755c6/src/addfips/addfips.py#L86) to use `open('rt', encoding='utf-8')` fixes the issue and seems like a good change independent of this Arelle issue.

**Comment by austinmatherne-wk** [comment]
Thanks for reporting the issue and providing detail!

This fix will require some regression testing on our end, but first can you confirm if [this branch](https://github.com/austinmatherne-wk/Arelle/tree/reset-locale) resolves the issue for you?

**Comment by zaneselvans** [comment]
Hi @austinmatherne-wk!

I disabled our context manager fix, and tried running the ETL using your branch as the source for Arelle, and it had no character encoding issues, so I think this change does resolve the issue we were having.

**Comment by zaneselvans** [comment]
Then I reverted to having our FERC XBRL extractor use the official Arelle package, but with the context manager fix still disabled, and was able to reproduce the failure, so it looks like this is definitely a fix for our issue.

**Comment by austinmatherne-wk** [comment]
Perfect. Locale changes require quite a bit of QA on our end (testing on multiple platforms and application types, GUI, CLI, and library). But I'll make sure this gets tested (and assuming no regressions) merged next week.
