### ISSUE TITLE
Distribute Arelle via conda-forge

### ISSUE THREAD

**Issue by zaneselvans** [Arelle/Arelle#506]
### What should we change and why?

We use conda / mamba to manage our data processing environments and simplify working with underlying binary dependencies. We also use Arelle to extract XBRL data from FERC filings. In order to distribute our packages which rely on Arelle via conda, we need a version of Arelle that's packaged using conda as well.

Previously we had been planning to package our fork of Arelle for distribution via conda-forge (See [this PR](https://github.com/conda-forge/staged-recipes/pull/21261)), but now that we've been able to get our [FERC XBRL Extractor](https://github.com/catalyst-cooperative/ferc-xbrl-extractor) [working with the official Arelle package](https://github.com/catalyst-cooperative/ferc-xbrl-extractor/issues/36), it doesn't make any sense for us to have a separate fork of Arelle.

We could package the official Arelle distribution instead, but it might make more sense for the real project owners to be in charge of the packaging, if it's something you'd find useful for the project.

Conda / mamba seem like they're mainly used by scientific / and data-oriented Python users, to help manage dependencies between packages that often have lots of C and Fortran extensions. The Python GIS stack is especially annoying to get installed with all the right binary versions outside of conda. I don't know who the primary user base is for Arelle, but it seems like it's at least adjacent to PyData users, particularly those working in finance, regulation, or public policymaking.

**Comment by sagesmith-wf** [comment]
Probably reasonable to add a workflow for it. Maybe use [this](https://github.com/marketplace/actions/publish-conda-package-to-anaconda-org) as a starting point?

**Comment by zaneselvans** [comment]
Okay, we've got an initial conda feedstock set up! https://github.com/conda-forge/arelle-release-feedstock 

We should test whether everything works when Arelle & its dependencies are installed from conda.

**Comment by zaneselvans** [comment]
I updated the feedstock to package 2.2.4 today, and also added entrypoints for the windows command line and gui applications, and updated several of the URLs to point at more useful resources. Happy to add whoever would be the appropriate person here as a maintainer on the feedstock whenever you like.

**Comment by sagesmith-wf** [comment]
👍 would @Arelle/arelle work?

**Comment by austinmatherne-wk** [comment]
As Sage suggested, if you can add the Arelle team, that would be ideal. Otherwise please include all members:

* @aaroncameron-wk 
* @allenbross-wf
* @austinmatherne-wk
* @derekgengenbacher-wf
* @hefischer
* @sagesmith-wf
* stevenbronson-wk

**Comment by zaneselvans** [comment]
So far as I can tell it can only accommodate individual accounts and not teams in the maintainer list. You'll get an invite to join the @conda-forge team and will have to accept it to get write access to the feedstock repository.

**Comment by zaneselvans** [comment]
There's a bot that checks for new PyPI releases and creates a new PR to update the conda feedstock with the new PyPI release. Unless dependencies have changed between versions, these PRs can typically just be merged. It's also possible [to tell the bot](https://conda-forge.org/docs/maintainer/infrastructure.html#conda-forge-admin-please-add-bot-automerge) to automatically merge these PRs if the CI passes.

**Comment by austinmatherne-wk** [comment]
Thanks @zaneselvans! I'll keep an eye on the feedstock repo to make sure it gets updated with our releases. If we run into issues I'll make sure to reach out.

**Comment by sagesmith-wf** [comment]
I have accepted the invite as well
