### ISSUE TITLE
validate/GFM plugin fails to load in frozen builds

### ISSUE THREAD

**Issue by austinmatherne-wk** [Arelle/Arelle#514]
### What happened?

The GFM validation plugin fails to load from the frozen builds because it [attempts to import from the EFM plugin](https://github.com/Arelle/Arelle/blob/1a294dcf6d6aa05f9fb2de698a8fd72f5003f0fc/arelle/plugin/validate/GFM/__init__.py#L7-L8) and the plugin namespace (`arelle.plugin.validate.*`) doesn't exist from the root directory where the plugins are moved during the build process. This appears to have been broken for a long time.

### If running from the command line, what command did you run?

arelleCmdLine --plugins validate/GFM

### Interface

CLI (arelleCmdLine), GUI (arelleGUI)

### Version

2.2.4

### Download

arelle.org (bundled Python), GitHub release (bundled Python)

### Operating System

Linux (Red Hat 7), Linux (Ubuntu 22.04), macOS 12 Monterey

**Comment by hermfischer** [comment]
GFM is quite obsolete, has there been any maintenance to it, is anybody using it?
