### ISSUE TITLE
PIP-installed plugin support breaks PluginManager.addPluginModule on Python < 3.10

### ISSUE THREAD

**Issue by paulwarren-wk** [Arelle/Arelle#591]
### What happened?

I have some code that calls:

```python
    PluginManager.addPluginModule("transforms/SEC")
```

On Python 3.9, I now get:
```
File ".../Arelle/arelle/PluginManager.py", line 502, in addPluginModule
    unloaded_arelle_plugins = entry_points(group='arelle.plugin', name=url)
TypeError: entry_points() got an unexpected keyword argument 'group'
```

From https://docs.python.org/3/library/importlib.metadata.html :

> The “selectable” entry points were introduced in importlib_metadata 3.6 and Python 3.10. Prior to those changes, entry_points accepted no parameters and always returned a dictionary of entry points,

The command line plugin management also calls this method, so I assume that that will break on older Python too.

### Interface

CLI (arelleCmdLine)

### Version

3e6658f08f12a2ab4edf522b22b86da7951fb17f

### Download

From source (git checkout)

### Operating System

Linux (Ubuntu 20.04)

**Comment by sagesmith-wf** [comment]
Thanks Paul, I will fix today
