### ISSUE TITLE
Supported Python versions is out of date

### ISSUE THREAD

**Issue by paulwarren-wk** [Arelle/Arelle#642]
### What happened?

`README.md` says:

> The implementation is in Python >= 3.7

but the code now makes use of typed collections (e.g. `list[int]`) which are only available in Python 3.9+.

It would be good to correct the above document, and also make the required Python version more prominent.   

There are also still a couple of places where there are conditionals relating to older versions, e.g. `typing.py` has:

```
if sys.version_info >= (3, 8):
    from typing import TypedDict  # pylint: disable=no-name-in-module
else:
    from typing_extensions import TypedDict
```

We should also consider adding a run-time check for the required version.

### Interface

CLI (arelleCmdLine)

### Version

5784cabd2347c7e42a48fa2114cb2cdd4ee33a1a

### Download

GitHub release (bundled Python)

### Operating System

Other (please specify)

**Comment by austinmatherne-wk** [comment]
We should update the README to clarify our support for Python 3.7. Arelle is intended to run on all Python versions still receiving security updates, which currently includes Python 3.7 and above (Python 3.7 will reach EOL on 2023-06-27, at which point we will stop testing against it). We have automated test coverage for Python 3.7 and higher. Due to the nature of type hints, it is not feasible to target them for multiple Python versions concurrently. The development tooling (mypy, flake8) targets the latest Python version (3.11), but as Steven mentioned, we intend to use it in such a way as not to prevent Arelle from running on earlier versions. If there is an issue in a specific module, please let us know.

**Comment by paulwarren-wk** [comment]
Ah, thanks for clarifying.  I'm not particularly familiar with Python typing support, but I don't think that `from __future__ import annotations` gets you everything available in 3.9+.  Specifically, the [explicit types for collections](https://mypy.readthedocs.io/en/stable/type_inference_and_annotations.html#explicit-types-for-collections) functionality doesn't work directly:

> Using type arguments (e.g. list[int]) on builtin collections like [list](https://docs.python.org/3/library/stdtypes.html#list), [dict](https://docs.python.org/3/library/stdtypes.html#dict), [tuple](https://docs.python.org/3/library/stdtypes.html#tuple), and [set](https://docs.python.org/3/library/stdtypes.html#set) only works in Python 3.9 and later. For Python 3.8 and earlier, you must use [List](https://docs.python.org/3/library/typing.html#typing.List) (e.g. List[int]), [Dict](https://docs.python.org/3/library/typing.html#typing.Dict), and so on.

For example, on Python 3.8.10, I get the following error when trying to validate an iXBRL file:

```
[exception:TypeError] Instance validation exception: 'type' object is not subscriptable, instance: testdoc.html - testdoc.html 
Traceback (most recent call last):
  File "/home/pdw/Arelle/arelle/Validate.py", line 108, in validate
    self.instValidator.validate(self.modelXbrl, self.modelXbrl.modelManager.formulaOptions.typedParameters(self.modelXbrl.prefixedNamespaces))
  File "/home/pdw/Arelle/arelle/ValidateXbrl.py", line 448, in validate
    for f in cast(set[ModelInlineFact], modelXbrl.factsInInstance):
TypeError: 'type' object is not subscriptable
```

The other issue I hit was a reprise of #591. Specifically, [this line](https://github.com/Arelle/Arelle/pull/593/files#diff-66c8376820d75f674b7add71ac44e4bdff81134ea56636875ce8f83522ecf514R502):

```python
if sys.version_info < (3, 10):
        unloaded_arelle_plugins = [e for e in entry_points().get('arelle.plugin', []) if e.name == url]
```

This fails because `entrypoints()` was returning an `EntryPoints` object, which doesn't implement the legacy dict interface.  This doesn't seem to fit with the [documentation](https://docs.python.org/3/library/importlib.metadata.html):

> The “selectable” entry points were introduced in importlib_metadata 3.6 and Python 3.10. Prior to those changes, entry_points accepted no parameters and always returned a dictionary of entry points, keyed by group. For compatibility, if no parameters are passed to entry_points, a SelectableGroups object is returned, implementing that dict interface. In the future, calling entry_points with no parameters will return an EntryPoints object. Users should rely on the selection interface to retrieve entry points by group.

Apparently, despite being on Python 3.7.3,  I was living in the future and `entry_points()` was returning an `EntryPoints` object.

**Comment by austinmatherne-wk** [comment]
#644 should resolve the cast errors on 3.7.

I'm unable to replicate the entry_points issue. It sounds like you might have had a version of importlib_metadata that's newer than what's [specified in requirements.txt](https://github.com/Arelle/Arelle/blob/e9c19caa37f9c2a2fa5dca3f56235cb6947003cf/requirements.txt#L3)? [Perhaps 6.0.0](https://github.com/Arelle/Arelle/pull/573/commits/dcf895aad6494a9b2d4a87ec0e19cb21e18db990#diff-4d7c51b1efe9043e44439a949dfd92e5827321b34082903477fd04876edb7552L3)?

**Comment by paulwarren-wk** [comment]
> I'm unable to replicate the entry_points issue. It sounds like you might have had a version of importlib_metadata that's newer than what's [specified in requirements.txt](https://github.com/Arelle/Arelle/blob/e9c19caa37f9c2a2fa5dca3f56235cb6947003cf/requirements.txt#L3)? [Perhaps 6.0.0](https://github.com/Arelle/Arelle/pull/573/commits/dcf895aad6494a9b2d4a87ec0e19cb21e18db990#diff-4d7c51b1efe9043e44439a949dfd92e5827321b34082903477fd04876edb7552L3)?

Yes, that's quite possible.  Unfortunately, I no longer have the setup that was causing problems, as I took it as an excuse to do an OS upgrade on the server.  It does look like installing as per `requirements.txt` would DTRT, so I'm happy for this part to be left as-is.
