### ISSUE TITLE
Consolidate duplicate CLI option declarations

### ISSUE THREAD

**Issue by austinmatherne-wk** [Arelle/Arelle#646]
### What should we change and why?

The command line options in [CntlrCmdLine.py](https://github.com/Arelle/Arelle/blob/cb8a61b3ed98207a075c81c36c8b27cb014493f6/arelle/CntlrCmdLine.py#L115-L117) have duplicate declarations to support all lowercase names:

```python
parser.add_option(
    "--noValidateTestcaseSchema",
    action="store_false",
    dest="validateTestcaseSchema",
    default=True,
    help=_("Validate testcases against their schemas."),
)
parser.add_option(
    "--novalidatetestcaseschema",
    action="store_false",
    dest="validateTestcaseSchema",
    default=True,
    help=SUPPRESS_HELP,
)
```

The option parser supports passing multiple param names to the same option declaration. So we should rewrite all of them to be like:

```python
parser.add_option(
    "--noValidateTestcaseSchema",
    "--novalidatetestcaseschema",
    action="store_false",
    dest="validateTestcaseSchema",
    default=True,
    help=_("Validate testcases against their schemas."),
)
```

**Comment by zubu007** [comment]
Did you solve it? Or can I make PR for it? I am a beginner in contributing and trying to find something to start with.

**Comment by austinmatherne-wk** [comment]
It isn't done yet, and we'd be happy to have you open a PR! 🙂
All of the duplicated options can be found [in the CntlrCmdLine.py module](https://github.com/Arelle/Arelle/blob/f14abeeddf2542740732a45f2729791c0df94496/arelle/CntlrCmdLine.py#L77-L369).

Please note that Arelle is used by regulatory agencies around the world, as well as companies that embed it in their products. As a result, we require a [CLA (contributor license agreement)](https://github.com/Arelle/Arelle/blob/master/CONTRIBUTING.md#contributor-license-agreements) to be signed and emailed before we can accept contributions from new community members. This is primarily to ensure that contributors don't claim copyright over their contributions, which could end up deployed at various organizations and within their products.

**Comment by zubu007** [comment]
I have signed the CLA license agreement. How do I send it to you?
Also I am working on this issue.

**Comment by austinmatherne-wk** [comment]
Awesome! You can email it to support@arelle.org

**Comment by zubu007** [comment]
Sent the file. Please check.

**Comment by austinmatherne-wk** [comment]
Got it. Thanks!
