### ISSUE TITLE
Load from OIM plugin creating corrupted xbrl (not closing line 2 comment)

### ISSUE THREAD

**Issue by davidtauriello** [Arelle/Arelle#655]
### What happened?

loaded data using the Load from OIM plugin in the GUI and saved the resulting .xbrl file

re-opening the resulting .xbrl file, arelle displays this message:

[xmlSchema:syntax] Comment not terminated, f6testOIMupdate.xbrl, line 13458, column 1 - f6testOIMupdate.xbrl 
**[xmlSchema:syntax] Start tag expected, '<' not found, f6testOIMupdate.xbrl, line 13458, column 1 - f6testOIMupdate.xbrl**

examining the resulting .xbrl file, the <!--commented line 2 is not closed after noting the file used for the extraction, so the whole document becomes invalid
 
not successfully loaded in 0.01 secs

### Interface

GUI (arelleGUI)

### Version

2.2.3 and 2.4.2

### Download

arelle.org (bundled Python)

### Operating System

Windows 10

**Comment by austinmatherne-wk** [comment]
Hi David,

Thank you for reporting. #656 should resolve this.

Austin

**Comment by davidtauriello** [comment]
Thanks for the quick response and help, @austinmatherne-wk - I'll look for this change in an upcoming release.

**Comment by austinmatherne-wk** [comment]
I'm happy to help.

We just cut a new release (2.6.0) that includes this fix.
