### ISSUE TITLE
Arelle CmdLine out _htm.xml file missing link:schemaRef @xlink:href to xsd schema

### ISSUE THREAD

**Issue by michaelchadfleming** [Arelle/Arelle#710]
### What happened?

Hello! Hope all is well! When we run arelleCmdLine with the command below, the out folder used to include a _htm.xml file that included the correct link:schemaRef @xlink:href to the xsd schema. However, with the latest master for 23.1 / 2.10.5 this line of code is now being deleted and causing numerous validation errors including [xbrl:schemaImportMissing]

Expected Line Of Code: <link:schemaRef xlink:href="dfin-20230331.xsd" xlink:type="simple"/>

Actual Result: Line of code is missing

[dfin-20230331.zip](https://github.com/Arelle/Arelle/files/11636273/dfin-20230331.zip)
[dfin-20230331_htm.zip](https://github.com/Arelle/Arelle/files/11636275/dfin-20230331_htm.zip)
[Log.zip](https://github.com/Arelle/Arelle/files/11636277/Log.zip)

### If running from the command line, what command did you run?

python arelleCmdLine.py --xdgConfigHome=C:\Users\maque\Desktop\TestArelle --plugins "C:\Users\maque\Desktop\TestArelle\Arelle\arelle\plugin\EdgarRenderer" --disclosuresystem efm-extended-pragmatic-all-years -f "C:\Users\maque\Desktop\TestArelle\samples\dfin-20230331.zip" -r "C:\Users\maque\Desktop\TestArelle\samples\Out" --logFile "C:\Users\maque\Desktop\TestArelle\samples\Out\Log.xml"

### Interface

CLI (arelleCmdLine)

### Version

2.10.5 downloaded master today 2023.06.02

### Download

GitHub release (bundled Python)

### Operating System

Windows 10

**Comment by austinmatherne-wk** [comment]
Hi @michaelchadfleming,

Where exactly are you getting that error? Also, what validation errors do you get if you try to validate that report on your system?

Thanks,
Austin Matherne

**Comment by michaelchadfleming** [comment]
Hi @austinmatherne-wk 

We see the error using Arelle validation. I was using SEC EFM pragmatic all years. I attached a the zip that includes the xml instance from the out folder after running the command line. Below is an image using Arelle GUI validation on this zip.
![image](https://github.com/Arelle/Arelle/assets/133998455/260850b3-15a3-4f32-8606-c00396d8ae9c)

[dfin-20230331_htm_xml_From_Arelle_Out_Folder.zip](https://github.com/Arelle/Arelle/files/11706547/dfin-20230331_htm_xml_From_Arelle_Out_Folder.zip)

**Comment by austinmatherne-wk** [comment]
Thanks for reporting. I've narrowed down the regression to #671. We'll get this fixed soon.

**Comment by hermfischer** [comment]
Problem seems to only occur when running with -f of the zip instead of -f to expanded files.

**Comment by austinmatherne-wk** [comment]
resolved in #712

**Comment by austinmatherne-wk** [comment]
Hi Chad,

The version of the inlineXbrlDocumentSet plugin in your screenshot appears to be an older version. Can you try updating to the latest release ([2.11.10](https://github.com/Arelle/Arelle/releases/tag/2.11.10)) and let me know if the issue persists?

**Comment by michaelchadfleming** [comment]
Thank you Austin :). The dev working on this updated that and its working as expected now :)
