### ISSUE TITLE
ESEF.2.5.1.imageDoesNotMatchItsFileExtension validation error triggers on jpg included in RP

### ISSUE THREAD

**Issue by tijmentekulveF19** [Arelle/Arelle#714]
### What happened?

When testing the new release an unexpected validation error occurred:

[ESEF.2.5.1.imageDoesNotMatchItsFileExtension] Header type jpg has wrong image type: .jpg - YourNextReport_BV-2022-12-31.xhtml 68

The image is a valid jpg file included in the reporting package with a jpg extension. The validation message should not be triggered.

When the images are embedded in the xhtml instead, the error is correctly not triggered. See "[img embedded] YourNextReport_BV-2022-12-31.zip".

### Documents

Images included in RP (Unexpected error):
[[img in rp] YourNextReport_BV-2022-12-31.zip](https://github.com/Arelle/Arelle/files/11651214/img.in.rp.YourNextReport_BV-2022-12-31.zip)

Images embedded in XHTML (No error as expected):
[[img embedded] YourNextReport_BV-2022-12-31.zip](https://github.com/Arelle/Arelle/files/11651204/img.embedded.YourNextReport_BV-2022-12-31.zip)

### Interface

GUI (arelleGUI)

### Version

2.10.5

### Download

arelle.org (bundled Python)

### Operating System

Windows 10

**Comment by austinmatherne-wk** [comment]
Hi @tijmentekulveF19,

The issue is that the ESEF plugin fails to detect files with the `.jpg` extension as JPEGs. We'll get this fixed. In the meantime if you change the file extension to `.jpeg` the validation should go away.

Thanks for reporting,
Austin Matherne

**Comment by austinmatherne-wk** [comment]
Hi @tijmentekulveF19,

This is fixed as of the latest release [2.10.6](https://github.com/Arelle/Arelle/releases/tag/2.10.6)
