### ISSUE TITLE
Update ESEF compliance to IFRS 2022

### ISSUE THREAD

**Issue by pazodoble** [Arelle/Arelle#748]
### What should we change and why?

**What happened?**
The ESMA submitted last year the ESEF Taxonomy 2022, which was made available on the 22nd December 2022 (see https://www.esma.europa.eu/document/esef-taxonomy-2022). The Validate ESMA ESEF plugin distributed with Arelle is the version 1.2020.03, which does not support the latest ESEF Taxonomy 2022 (based on the IFRS 2022).

Here is the message returned by Arelle when running validation on new ESEF packages:
[ESEF.RTS.ifrsRequired] RTS on ESEF requires IFRS taxonomy.

**Documents**
You can download any ESEF package based on the ESEF/IFRS 2021 taxonomies from https://filings.xbrl.org. The ESEF validation will work. If you upgrade package to the ESEF / IFRS 2022 taxonomies to be used by European companies for FY 2023 reporting, the ESEF validation will NOT work with the above message.

**If running from the command line, what command did you run?**
arelleCmdLine.exe --file "%INSTANCEFILE%" --plugins "validate/ESEF" --disclosureSystem esef --validate --calcDecimals --calcDeduplicate --utr --formulaUnsatisfiedAsser --formulaUnsatisfiedAsserError --internetConnectivity online --logFile validation_report.txt 1> trace_log.txt 2>&1

**Interface**
GUI (arelleGUI) and Command Line (arelleCmdLine)

**Version**
2.10.7

**Download**
https://arelle.org/arelle/documentation/esma-esef-installation/
then Download "Win 64 Installer" (eu)

**Operating Systems**
Windows 10, Windows 11, Windows Server 2016, Windows Server 2019

**Comment by austinmatherne-wk** [comment]
Hi,

There is a separate plugin for ESEF 2022 `--plugins "validate/ESEF_2022"`. If you have issues with the new plugin please open a new issue.
