### ISSUE TITLE
Document Fork and Pull Request Flow

### ISSUE THREAD

**Issue by austinmatherne-wk** [Arelle/Arelle#837]
### What should we change and why?

We [link to](https://github.com/Arelle/Arelle/blob/1db177c94a2e597ab3e339b80f039430d1fec27d/CONTRIBUTING.md?plain=1#L58) a long detailed how to from GitHub in our contributing docs for how to open a pull request. Based on conversations with the community, we should provide a tldr version of how to fork the repo, work on a branch, push changes, and open a pull request.

**Comment by Rjchauhan18** [comment]
Hello @austinmatherne-wk 
I would like to work on this issue.
Can you please assign this issue to me ?

**Comment by austinmatherne-wk** [comment]
Hi @Rjchauhan18. I'm happy to! Thanks for expressing desire in contributing to Arelle.

Please note this project is embedded in a number of products and government software solutions. Consequently we do [require a CLA](https://github.com/Arelle/Arelle/blob/master/CONTRIBUTING.md#how-to-become-a-code-contributor) to be signed by new contributors before we can accept and merge PRs. Let me know if you have any questions.

**Comment by Rjchauhan18** [comment]
Hey @austinmatherne-wk ,
I just mail my individual signed CLA form to [Support@arelle.org](mailto:Support@arelle.org) . so , now I will get any conformation mail or something .

**Comment by Rjchauhan18** [comment]
And I have change the tldr version on contribution.md In the place of [Setting Up Your Environment](https://github.com/Arelle/Arelle/blob/1db177c94a2e597ab3e339b80f039430d1fec27d/CONTRIBUTING.md#setting-up-your-environment) ?

**Comment by austinmatherne-wk** [comment]
Hi @Rjchauhan18,

We received the CLA. Thank you!

The changes look good. I'd like to continue having pyenv and venv in the documentation (most of the team uses them). What issues did you have with it exactly?

**Comment by Rjchauhan18** [comment]
I may be got a problem because I have already installed virtualenv package and while install Pyenv both the package might have clashed.

**Comment by Rjchauhan18** [comment]
One more thing for CLI : 

### **`Command : python arelleCmdLine.py ` is not working giving this error** 

![image](https://github.com/Arelle/Arelle/assets/113838908/66779006-c678-4f64-ac4e-feda62f65d1e)

---

### **We should use this commmad : ` python arelleCmdLine.py --version` or `python arelleCmdLine.py --help`** 

![image](https://github.com/Arelle/Arelle/assets/113838908/9578c61f-61ed-497c-bd98-c14216c9bbe7)

**Comment by austinmatherne-wk** [comment]
Hi again. `python arelleCmdLine.py --help` is a good suggestion if you'd like to add it. Thanks for making these changes!

**Comment by austinmatherne-wk** [comment]
PR merged. Thanks for the contribution!
