### ISSUE TITLE
SchemaImportMissing error when loading Japanese XBRL instance document created with Inline XBRL Document Set plug-in

### ISSUE THREAD

**Issue by kfollett-pd** [Arelle/Arelle#841]
### What happened?

Loading Japanese XBRL instance documents created by Inline XBRL Document Set plug-in (dated 2023-08-23T16:06:30 UTC) results in SchemaImportMissing error.

![SchemaImportMissingError](https://github.com/Arelle/Arelle/assets/27394802/1a92dd0a-ee23-4fe5-8e19-0c944754d0be)

![InlineXBRLDocumentSetPlugIns](https://github.com/Arelle/Arelle/assets/27394802/5b6e6448-2b2e-49d3-94fb-bd623bba3a6f)

Steps to reproduce:

 1.  Extract JapaneseXBRLReport.zip
 2.  Open Arelle GUI
 3.  File -> Open File -> manifest.xml
 4.  Tools -> Save target document
 5.  File -> Open File -> tse-acedjpfr-19990-2023-06-30-01-2023-08-18_extracted.xbrl

### Documents

[JapaneseXBRLReport.zip](https://github.com/Arelle/Arelle/files/12428902/JapaneseXBRLReport.zip)

### Interface

GUI (arelleGUI)

### Version

2.13.4

### Download

GitHub release (bundled Python)

### Operating System

Windows 10

**Comment by austinmatherne-wk** [comment]
Thanks for reporting @kfollett-pd.

This should be resolved once #849 is merged and released.

**Comment by austinmatherne-wk** [comment]
This should be resolved in the latest release (2.13.6)

**Comment by kfollett-pd** [comment]
This issue starts occurring again from version 2.14.0.

**Comment by austinmatherne-wk** [comment]
Confirmed. @hermfischer-wf

Opening the attached doc from the GUI produces an error:

> [arelle:nonIxdsDocument] Non-inline file is not loadable into an Inline XBRL Document Set. - IXDS 0101010-acbs01-tse-acedjpfr-19990-2023-06-30-01-2023-08-18-ixbrl.htm, 0102010-acpl01-tse-acedjpfr-19990-2023-06-30-01-2023-08-18-ixbrl.htm, ... 

And the save taget instance dialog throws an exception:

<img width="632" alt="Screenshot 2023-10-08 at 3 18 47 PM" src="https://github.com/Arelle/Arelle/assets/46454775/adcbd252-cacf-489f-aaac-d9a24531e505">

**Comment by austinmatherne-wk** [comment]
@kfollett-pd This should be resolved again with the latest release ([2.18.0](https://github.com/Arelle/Arelle/releases/tag/2.18.0)). Also we're planning to add a test to make sure this doesn't break again.
