### ISSUE TITLE
Command line input zipped iXBRL package resulting in _htm.xml file with extra schemaRef causing errors

### ISSUE THREAD

**Issue by michaelchadfleming** [Arelle/Arelle#873]
### What happened?

When we run command line with iXBRL zipped package as input we expect to get valid _htm.xml file that is the traditional XBRL extracted instance. However, we are getting a instance created that has extra lines of code that have validation errors.

### Documents

![MicrosoftTeams-image (38)](https://github.com/Arelle/Arelle/assets/133998455/644051fb-20d5-4723-a96d-3c3bd83bc7cd)

### If running from the command line, what command did you run?

@ECHO OFF SET PYTHONPATH=C:\python39 SET PATH=C:\python39;%PATH%     C:\python39\python.exe "C:\re3\Renderer233\arellecmdline.py" --xdgConfigHome=C:\re3 --plugins "C:\re3\Renderer233\arelle\plugin\Edgar233" --disclosuresystem efm-pragmatic -f "C:\re3\samples\input\cik0000770116-imt-20230724-Version04-1" -r "C:\re3\samples\input\Output" --logFile "C:\re3\samples\Input\Log.xml"

### Interface

CLI (arelleCmdLine)

### Version

Downloaded master September 25, 2023

### Download

From source (git checkout)

### Operating System

Windows 10

**Comment by michaelchadfleming** [comment]
[23.3.test_different_inputs.zip](https://github.com/Arelle/Arelle/files/12716264/23.3.test_different_inputs.zip)
This attached zip shows that Arelle creates different files depending on if the input files are zipped or extracted. The zipped input files results in errors caused by extra link:schemaRef

**Comment by austinmatherne-wk** [comment]
Hi @michaelchadfleming,

Please check what versions of Arelle and the EdgarRenderer plugin you're using. It appears you're trying to use the EFM 23.3 release of the EdgarRenderer. v2.14.0 is the minimum version of Arelle that supports the EFM 23.3 release of the EdgarRenderer. If it's still not working with the latest version, please report this to the SEC (StructuredData@sec.gov). They develop and maintain the EdgarRenderer plugin.

Thanks,
Austin

**Comment by michaelchadfleming** [comment]
I emailed Structured Data with details. Thank you Austin
