### ISSUE TITLE
Command line documentation formatting tweaks

### ISSUE THREAD

**Issue by paulwarren-wk** [Arelle/Arelle#944]
### What should we change and why?

I've just been made aware of the [command line documentation](https://arelle.readthedocs.io/en/2.17.1/command_line.html) which is great ­– much easier to work with than scrolling through pages and pages of usage message.

I think it would be better if backticks were used for all command line options, as this would (I think) prevent line-wrapping in the option:

![image](https://github.com/Arelle/Arelle/assets/45077928/257e2221-1676-4220-9a9d-9aa47fc5d230)

i.e. change this to:

| name | description|
|-|-|
|`--logLevelFilter=LOGREGX`|Regular expression filter for logLevel. (E.g., to not match -semantic levels, --logLevelFilter=(?!^.-semantic$)(.+).|

Currently it's only used for values passed to options (the `LOGREGX` bit here).

EDIT - backticks alone clearly aren't enough to prevent the wrapping, so it'd also need some `white-space: nowrap` CSS.

I also think it would be good to make more liberal use of backticks in the descriptions where there are literal values that you'd use in the option, e.g. the `online` and `offline` in this bit:

![image](https://github.com/Arelle/Arelle/assets/45077928/afcb67bf-ab78-4836-95e0-defb45d4b753)

I'm happy to make these changes, but wanted to check that there wasn't an existing style guide/convention, or preferences for something different (@allenbross-wf ?)

**Comment by austinmatherne-wk** [comment]
The suggested changes get a 👍  from me.

There isn't a style guide. When we migrate to argparse we'll move to [sphinx-argparse](https://sphinx-argparse.readthedocs.io/en/stable/) to generate the CLI documentation, so this is a bit of a stopgap.
