### ISSUE TITLE
IdentifierSchemeMustBeLEI error when validating packages that use both ESEF and DK GAAP

### ISSUE THREAD

**Issue by IulianBogdan** [Arelle/Arelle#966]
### What happened?

When using the Arrele command line to validate a package that is using both ESEF 2022 and DK GAAP 2022, I get the following validation error:
`<entry code="message:con_IdentifierSchemeMustBeLEI" level="error">
		<message formulaMessage="invalidIdentifierFormat: According to the Regulatory Technical Standards on European Single Electronic Format, all issuers shall..." label="con_IdentifierSchemeMustBeLEI">[message:con_IdentifierSchemeMustBeLEI] invalidIdentifierFormat: According to the Regulatory Technical Standards on European Single Electronic Format, all issuers shall identify themselves using ISO 17442 legal entity identifiers on the XBRL context entity identifiers and schemes. Please make sure all XBRL context entity identifier schemes are provided with the value &quot;http://standards.iso.org/iso/17442&quot;. - https://www.esma.europa.eu/taxonomy/2022-03-24/esef_cor-for.xml 20747</message>
		<ref href="https://www.esma.europa.eu/taxonomy/2022-03-24/esef_cor-for.xml#con_IdentifierSchemeMustBeLEI" sourceLine="20747">
			<property name="id" value="con_IdentifierSchemeMustBeLEI"/>
			<property name="label" value="valueAssertion"/>
			<property name="aspectModel" value="dimensional"/>
			<property name="implicitFiltering" value="true"/>
			<property name="test" value="xfi:identifier-scheme($identifier) eq &quot;http://standards.iso.org/iso/17442&quot;"/>
		</ref>
	</entry>`

**Context:**
The package is using the company's CVR (VAT) code as the LEI code, which triggers the error. The problem is that using the CVR as LEI is a valid option for DK GAAP taxonomies.
We set the authority=DK in the parameters, which I assumed would be the correct configuration for this use case.

We get the same result when running Arelle on Ubuntu 20.04.

### If running from the command line, what command did you run?

.\arelleCmdLine.exe --file 'test_package.zip' --logFile validation.xml --logLevel debug --collectProfileStats --parameters authority=DK --validate  --calc xbrl21-dedup --disclosureSystem esef --utr  --internetConnectivity online --internetTimeout 0 --internetRecheck never --plugins 'validate/ESEF' --packages 'ESEF_20220324.zip|IFRS_20220324.zip|DK_ARL_20221001.zip'

### Interface

CLI (arelleCmdLine)

### Version

2.17.3 and 2.17.4

### Download

GitHub release (bundled Python)

### Operating System

Windows 11

**Comment by austinmatherne-wk** [comment]
Hi Bogdan,

That validation is coming from a formula assertion in the ESEF taxonomy itself, so not something that Arelle has specifically coded up. We do have that formula disabled for UKFRC, but not for DK. Can you provide a link to a reporting manual or somewhere else that defines the valid identifier scheme for DK GAAP? We can update the plugin to ignore that taxonomy formula if we have documentation showing that it doesn't apply.

In the meantime you can disable the formula by providing a negative lookahead to the formula run IDs. Here's the value that's used for UKFRC validation:

```bash
python arelleCmdLine.py ... --formulaRunIDs "(?!con_IdentifierSchemeMustBeLEI|lei-identifier-scheme)"
```

**Comment by IulianBogdan** [comment]
Hi Austin, thanks for replying, I attached the official document you requested, the information you are looking for is at page 35.
My colleagues translated the whole section, if it helps:

> Short description:
> If the context identifier scheme is 'http://standards.iso.org/iso/17442', all context identifiers must be
> equal to the value of the 'gsd:LegalEntityIdentifierOfReportingEntity' field.
> If the context identifier scheme is 'http://www.dcca.dk/cvr', all context identifiers must be equal to
> the value of the field 'gsd:IdentificationNumberCvrOfReportingEntity'
> Announcement:
> TR15: If the context identifier scheme is 'http://standards.iso.org/iso/17442', all contexts must
> identifiers be equal to the value of the field 'gsd:LegalEntityIdentifierOfReportingEntity'. If context
> identifier scheme is 'http://www.dcca.dk/cvr', all context identifiers must be equal to the value of
> field 'gsd:IdentificationNumberCvrOfReportingEntity'. Contact your system supplier.
> Application:
> ESEF
> All report types

[Oversigt over tekniske regler ved indsendelse af digitale årsrapporter_ERST.pdf](https://github.com/Arelle/Arelle/files/13686620/Oversigt.over.tekniske.regler.ved.indsendelse.af.digitale.arsrapporter_ERST.pdf)
