### ISSUE TITLE
Plug-In DQC Partially Broken

### ISSUE THREAD

**Issue by michaelchadfleming** [Arelle/Arelle#978]
### What happened?

We are getting false positive DQC 22.0.1 invalid warning unallowable member EliminationsAndReconcilingItemsMember
[prod_export_11_28.zip](https://github.com/Arelle/Arelle/files/13503578/prod_export_11_28.zip)

Findings after initial investigation: we have observed no obvious Arelle misconfiguration, further, we also could not reproduce the error by using the GUI application. Having said that, we were able to reproduce the error by invoking Arelle via command line. 

1. A barebones document (attached) was exported using older Arelle 2.11.8 (XULE 23604.2), no DQC error was present in the validation log. See the document attached to the ticket.
2. Arelle was started in command line mode on a Windows machine, latest versions were used: Arelle 2.17.6 XULE 23663, DQC v22.0.1
The document was validated, DQC errors were being printed:
![image](https://github.com/Arelle/Arelle/assets/133998455/f8996ba7-d581-4e65-912b-99354b5f1fdf)

3. The error was also visible with old XULE 23570.2 and DQC v20 , but up-to-date Arelle 2.17.6
![image](https://github.com/Arelle/Arelle/assets/133998455/e43a9726-da6b-4a3e-ae9b-49f897f4b885)

4. With Arelle 2.11.8 the error is no longer encountered:
![image](https://github.com/Arelle/Arelle/assets/133998455/b56cdad1-8bab-4c1e-85cb-7b55d361a4ee)

This leads us to believe that there is likely an issue with a newer Arelle version where when invoked through command line, DQC validation for US.0001.70 fails. This particular rule uses metadata from XULE context (see https://github.com/DataQualityCommittee/dqc_us_rules/blob/master/dqc_us_rules/source/us/2023/DQC_0001.xule#L723), so there might be an issue with it's population.

### Documents

[nav_-_ex_26_09-30.zip](https://github.com/Arelle/Arelle/files/13491507/nav_-_ex_26_09-30.zip)

### If running from the command line, what command did you run?

When testing on a Windows machine, we used the following command line call for starting a local arelle webserver:
python -u .\arelleCmdLine.py --webserver=0.0.0.0:8088 --plugins="C:\pathto\EdgarRenderer|C:\pathto\SEC|C:\pathto\DQC.py" --dqc-replace-rule-set-map="C:\pathto\rulesetMap.json" --logLevel=warning
And for calling REST API (project archive is passed in request body):
http://localhost:8088/rest/xbrl/validation?disclosure-system=efm-pragmatic&media=zip&copyInlineFilesToOutput=true&copyXbrlFilesToOutput=true&saveViewer=false&zipXbrlFilesToOutput=true&saveTargetInstance=true

In the application we use an additional command line option for running arelle in offline mode:
python -u .\arelleCmdLine.py --webserver=0.0.0.0:8088 --plugins="C:\pathto\EdgarRenderer|C:\pathto\SEC|C:\pathto\DQC.py" --dqc-replace-rule-set-map="C:\pathto\rulesetMap.json" --logLevel=warning --internetConnectivity=offline
And additionally we use the Edgar renderer plugin in our REST API url:
http://localhost:8088/rest/xbrl/validation?disclosure-system=efm-pragmatic&media=zip&plugins=EdgarRenderer&copyInlineFilesToOutput=true&copyXbrlFilesToOutput=true&saveViewer=false&zipXbrlFilesToOutput=true&saveTargetInstance=true

### Interface

CLI (arelleCmdLine), Python library (pip install)

### Version

Arelle 2.17.6

### Download

GitHub release (bundled Python)

### Operating System

Windows 11

**Comment by michaelchadfleming** [comment]
I discussed with XBRL.US and we believe this is not from XBRL.US code. This appears to be from the SEC's DQC implementation. The primary risk appears to be that these errors might show in SEC Test and Live Filing Submissions Results reports

**Comment by austinmatherne-wk** [comment]
Hi @michaelchadfleming,

I'm having trouble replicating the error with the attached document.

1. Can you double check that you uploaded the correct document?
2. What plugin is `C:\pathto\SEC` referring to?
3. Do you get the same error if you use the bundled EdgarRenderer and DQC plugins (`plugins="EdgarRenderer|validate\DQC"`)? 

Thanks,
Austin Matherne

**Comment by michaelchadfleming** [comment]
Hi @austinmatherne-wk 

Thank you for looking into this! I hope all is well! :)

I forwarded your questions to the development team encountering this issue. I'll respond back if they respond. This development team discovered that they only get incorrect validation results if there are separate linkbases xml files. They are getting correct validation results if the link:linkbase's are included in the xsd schema. With that being said I believe this bug become lower priority especially since it can't be reproduced on your end or Campbell's end. Thank you as always Austin and have a wonderful weekend! :)

**Comment by michaelchadfleming** [comment]
Hi @austinmatherne-wk Our developer responded with the following comments:

I did some more debugging based on comments from Arelle development team:

1. Can you double check that you uploaded the correct document?
I downloaded the prod_export_11_28.zip project package from the github issue ([https://github.com/Arelle/Arelle/issues/978)](https://github.com/Arelle/Arelle/issues/978%29) and successfully used it to reproduce the bug.

2. What plugin is C:\pathto\SEC referring to?
C:\pathto\SEC is referring to the bundled plugin\transforms\SEC plugin.

3. Do you get the same error if you use the bundled EdgarRenderer and DQC plugins (plugins="EdgarRenderer|validate\DQC")?"
In our application we use arelle source code, which does not come bundled with EdgarRenderer, DQC or xule plugins. For this reason, we fetch these plugins from their respective repositories and running the above command with plugins missing does not result in any output.
However, the Windows installation package does come bundled with all these plugins. I used the Windows package from the command line in the following way to include bundled plugins:
.\arelleCmdLine.exe --webserver=0.0.0.0:8088 --plugins="EdgarRenderer|validate\DQC.py" --dqc-replace-rule-set-map="C:\pathto\rulesetMap.json" --logLevel=warning
I also tried removing the DQC ruleset replacement argument:
.\arelleCmdLine.exe --webserver=0.0.0.0:8088 --plugins="EdgarRenderer|validate\DQC.py" --logLevel=warning
In both cases and while using the same project package (prod_export_11_28.zip) I am getting the following error:
![Uploading image.png…]()
I also ran validation from command line directly (without starting a webserver) using the following command build according  to the one provided in a previous comment:
python .\arelleCmdLine.py --plugins="C:\pathto\DQC.py|C:\pathto\EFM" --dqc-replace-rule-set-map="C:\pathto\rulesetMap.json" --disclosureSystem "efm-pragmatic-all-years" -f "C:\pathto\prod_export_11_28.zip" -v --logfile "C:\pathto\ArelleDqcEFMValidationResult1.xml"
The false positive with rule DQC.US.0001.70 did not reproduce while running validation this way, but using these arguments for starting a webserver resulted in the same validation error as can be seen above.

**Comment by austinmatherne-wk** [comment]
Hi Chad,

I'm still unable to replicate the issue (I don't get the error from the webserver or CLI with that document).

If the error is from the SEC DQC rule implementations you can remove the `DQC.py` plugin and `-dqc-replace-rule-set-map` argument and you should still receive the error. Is that the case?

**Comment by michaelchadfleming** [comment]
@austinmatherne-wk Thank you Austin for looking into this. :) Our developers mentioned that it's working now in at least two situations. They unfortunately don't have the capacity right now to investigate the scenarios where it isn't working, but they plan to circle back to this at a later date. Therefore, since you're unable to replicate the issue, I'm going to close this issue for now. Thank you and have a wonderful day :)
