### ISSUE TITLE
Add alert for duplicated facts in reports when a taxonomy does not have a disclosure system

### ISSUE THREAD

**Issue by BiancaParsePort** [Arelle/Arelle#991]
### What should we change and why?

Arelle should raise an alert about duplicate facts in any report, regardless of whether the taxonomy has a disclosure system.  

Currently, Arelle raises an error about duplicate facts when a taxonomy has a disclosure system. Though, as a user checking my package, it would always be beneficial to know when there are duplicated facts in my report, even if the taxonomy I am using does not contain a disclosure system, for example DKGAAP.

**Comment by austinmatherne-wk** [comment]
Hi Bianca,

Can you provide more details about the use case for this?

Arelle raises an error or warning for duplicate facts for a disclosure system if the jurisdiction that disclosure system represents has a rule forbidding a type of duplicate fact. In other jurisdictions duplicate facts are permitted and sometimes expected, so a warning for all reports could be confusing. There's also the issue of defining precisely what a duplicate fact is. Not all jurisdictions use the same definition of "duplicate". For example, are two facts for Assets on December 31st 2023 duplicates if they have different values but the same context and unit? What about if they have different values, but overlapping decimals (such as `1000` with `-3` and `1100` with `-2`)?

**Comment by austinmatherne-wk** [comment]
@BiancaParsePort we're going to add an option for duplicate fact validation. You can track the work with #1001
